steps:
  - id: 'store-market-secrets'
    name: 'node:18.20.1'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Appending secrets to .env.production..."
        echo "$$MARKET_CONFIG" > ./.env.production
    secretEnv: ['MARKET_CONFIG']

  - id: 'debug-secrets'
    waitFor: ['store-market-secrets']
    name: 'node:18.20.1'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Contents of .env.production after modification:"
        cat ./.env.production

  - id: 'build'
    waitFor: ['debug-secrets']
    name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/marketplace:latest',
        '-t',
        'gcr.io/$PROJECT_ID/marketplace:$SHORT_SHA',
        '--build-arg',
        'COMMIT_SHA=$COMMIT_SHA',
        '.',
      ]

  - id: 'push'
    waitFor: ['build']
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/marketplace:$SHORT_SHA']

  - id: 'deploy'
    waitFor: ['push']
    name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'marketplace'
      - '--image'
      - 'gcr.io/$PROJECT_ID/marketplace:$SHORT_SHA'
      - '--region'
      - 'us-east4'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
availableSecrets:
  secretManager:
  - versionName: ${_CONFIG_MARKET_SECRET_NAME}
    env: 'MARKET_CONFIG'
substitutions:
  _CONFIG_MARKET_SECRET_NAME: path/to/market-secret
timeout: 900s
