FROM node:16

# Set working directory
WORKDIR /home/node/app

# Copy package.json and yarn.lock
COPY package.json ./
COPY yarn.lock ./

# Install dependencies
RUN yarn install

# Define build-time arguments
ARG REACT_APP_CSP
ARG REACT_APP_SHARETRIBE_MARKETPLACE_CURRENCY
ARG REACT_APP_SHARETRIBE_SDK_CLIENT_ID
ARG REACT_APP_STRIPE_PUBLISHABLE_KEY
ARG REACT_APP_SHARETRIBE_SDK_CLIENT_SECRET
ARG REACT_APP_MAPBOX_ACCESS_TOKEN
ARG REACT_APP_MARKETPLACE_ROOT_URL
ARG REACT_APP_ENV
ARG REACT_APP_SHARETRIBE_USING_SSL
ARG REACT_APP_AVAILABILITY_ENABLED
ARG REACT_APP_DEFAULT_SEARCHES_ENABLED

# Set environment variables
ENV PORT=4000
ENV NODE_ENV=production
ENV REACT_APP_CSP=$REACT_APP_CSP
ENV REACT_APP_SHARETRIBE_MARKETPLACE_CURRENCY=$REACT_APP_SHARETRIBE_MARKETPLACE_CURRENCY
ENV REACT_APP_SHARETRIBE_SDK_CLIENT_ID=$REACT_APP_SHARETRIBE_SDK_CLIENT_ID
ENV REACT_APP_STRIPE_PUBLISHABLE_KEY=$REACT_APP_STRIPE_PUBLISHABLE_KEY
ENV REACT_APP_SHARETRIBE_SDK_CLIENT_SECRET=$REACT_APP_SHARETRIBE_SDK_CLIENT_SECRET
ENV REACT_APP_MAPBOX_ACCESS_TOKEN=$REACT_APP_MAPBOX_ACCESS_TOKEN
ENV REACT_APP_MARKETPLACE_ROOT_URL=$REACT_APP_MARKETPLACE_ROOT_URL
ENV REACT_APP_ENV=$REACT_APP_ENV
ENV REACT_APP_SHARETRIBE_USING_SSL=$REACT_APP_SHARETRIBE_USING_SSL
ENV REACT_APP_AVAILABILITY_ENABLED=$REACT_APP_AVAILABILITY_ENABLED
ENV REACT_APP_DEFAULT_SEARCHES_ENABLED=$REACT_APP_DEFAULT_SEARCHES_ENABLED

# Copy the source code
COPY . .

# Expose port
EXPOSE 4000

# Build the application
RUN yarn run build

# Set user to node
USER node

# Command to start the app
CMD ["yarn", "start"]
