FROM node:18.20.1

ARG COMMIT_SHA
ENV BUILD_SHA ${COMMIT_SHA}

WORKDIR /usr/src/app

COPY . .

ARG MYSECRET
ENV MYSECRET ${MYSECRET}

ARG MYSECRET2
ENV MYSECRET2 ${MYSECRET2}

ARG ENV_FILE
ARG CONFIG_SECRET_NAME

ENV ENV_FILE ${ENV_FILE}
ENV CONFIG_SECRET_NAME ${CONFIG_SECRET_NAME}
ENV NODE_ENV=production
ENV PORT=8080

RUN yarn install
RUN yarn build
CMD ["yarn", "start", "echo MYSECRET during build: ${MYSECRET}", "echo ENV_FILE during build: ${ENV_FILE}"]
