FROM node:18.20.1

ARG COMMIT_SHA
ENV BUILD_SHA ${COMMIT_SHA}

WORKDIR /usr/src/app

COPY . .

ARG ENV_FILE
ARG CONFIG_SECRET_NAME
ARG WEBAPP_CONFIG

ENV ENV_FILE ${ENV_FILE}
ENV CONFIG_SECRET_NAME ${CONFIG_SECRET_NAME}
ENV WEBAPP_CONFIG ${WEBAPP_CONFIG}
ENV CLOUD_BUILD=true
ENV NODE_ENV=production
ENV PORT=8080

RUN yarn install
RUN yarn build
CMD ["yarn", "start"]
