/////////////////////////////////////////////////////////
// Configurations related to listing.                  //
// Main configuration here is the extended data config //
/////////////////////////////////////////////////////////

// Note: The listingFields come from listingFields asset nowadays by default.
//       To use this built-in configuration, you need to change the overwrite from configHelper.js
//       (E.g. use mergeDefaultTypesAndFieldsForDebugging func)

/**
 * Configuration options for listing fields (custom extended data fields):
 * - key:                           Unique key for the extended data field.
 * - scope (optional):              Scope of the extended data can be either 'public' or 'private'.
 *                                  Default value: 'public'.
 *                                  Note: listing doesn't support 'protected' scope atm.
 * - schemaType (optional):         Schema for this extended data field.
 *                                  This is relevant when rendering components and querying listings.
 *                                  Possible values: 'enum', 'multi-enum', 'text', 'long', 'boolean'.
 * - enumOptions (optional):        Options shown for 'enum' and 'multi-enum' extended data.
 *                                  These are used to render options for inputs and filters on
 *                                  EditListingPage, ListingPage, and SearchPage.
 * - listingTypeConfig (optional):  Relationship configuration against listing types.
 *   - limitToListingTypeIds:         Indicator whether this listing field is relevant to a limited set of listing types.
 *   - listingTypeIds:                An array of listing types, for which this custom listing field is
 *                                    relevant and should be added. This is mandatory if limitToListingTypeIds is true.
 * - categoryConfig (optional):     Relationship configuration against categories.
 *   - limitToCategoryIds:            Indicator whether this listing field is relevant to a limited set of categories.
 *   - categoryIds:                   An array of categories, for which this custom listing field is
 *                                    relevant and should be added. This is mandatory if limitToCategoryIds is true.
 * - filterConfig:                  Filter configuration for listings query.
 *    - indexForSearch (optional):    If set as true, it is assumed that the extended data key has
 *                                    search index in place. I.e. the key can be used to filter
 *                                    listing queries (then scope needs to be 'public').
 *                                    Note: Flex CLI can be used to set search index for the key:
 *                                    https://www.sharetribe.com/docs/references/extended-data/#search-schema
 *                                    Read more about filtering listings with public data keys from API Reference:
 *                                    https://www.sharetribe.com/api-reference/marketplace.html#extended-data-filtering
 *                                    Default value: false,
 *   - filterType:                    Sometimes a single schemaType can be rendered with different filter components.
 *                                    For 'enum' schema, filterType can be 'SelectSingleFilter' or 'SelectMultipleFilter'
 *   - label:                         Label for the filter, if the field can be used as query filter
 *   - searchMode (optional):         Search mode for indexed data with multi-enum schema.
 *                                    Possible values: 'has_all' or 'has_any'.
 *   - group:                         SearchPageWithMap has grouped filters. Possible values: 'primary' or 'secondary'.
 * - showConfig:                    Configuration for rendering listing. (How the field should be shown.)
 *   - label:                         Label for the saved data.
 *   - isDetail                       Can be used to hide detail row (of type enum, boolean, or long) from listing page.
 *                                    Default value: true,
 * - saveConfig:                    Configuration for adding and modifying extended data fields.
 *   - label:                         Label for the input field.
 *   - placeholderMessage (optional): Default message for user input.
 *   - isRequired (optional):         Is the field required for providers to fill
 *   - requiredMessage (optional):    Message for those fields, which are mandatory.
 */
export const listingFields = [
  // {
  //   "scope": "public",
  //   "label": "Gears",
  //   "key": "gears",
  //   "schemaType": "long",
  //   "numberConfig": {
  //     "minimum": 1,
  //     "maximum": 24
  //   },
  //   "filterConfig": {
  //     "indexForSearch": true,
  //     "group": "primary",
  //     "label": "Gears"
  //   }
  // }
  // {
  //   key: 'bikeType',
  //   scope: 'public',
  //   schemaType: 'enum',
  //   enumOptions: [
  //     { option: 'city-bikes', label: 'City bikes' },
  //     { option: 'electric-bikes', label: 'Electric bikes' },
  //     { option: 'mountain-bikes', label: 'Mountain bikes' },
  //     { option: 'childrens-bikes', label: "Children's bikes" },
  //   ],
  //   categoryConfig: {
  //     limitToCategoryIds: true,
  //     categoryIds: ['cats'],
  //   },
  //   filterConfig: {
  //     indexForSearch: true,
  //     filterType: 'SelectMultipleFilter', //'SelectSingleFilter',
  //     label: 'Bike type',
  //     group: 'primary',
  //   },
  //   showConfig: {
  //     label: 'Bike type',
  //     isDetail: true,
  //   },
  //   saveConfig: {
  //     label: 'Bike type',
  //     placeholderMessage: 'Select an option…',
  //     isRequired: true,
  //     requiredMessage: 'You need to select a bike type.',
  //   },
  // },
  // {
  //   key: 'tire',
  //   scope: 'public',
  //   schemaType: 'enum',
  //   enumOptions: [
  //     { option: '29', label: '29' },
  //     { option: '28', label: '28' },
  //     { option: '27', label: '27' },
  //     { option: '26', label: '26' },
  //     { option: '24', label: '24' },
  //     { option: '20', label: '20' },
  //     { option: '18', label: '18' },
  //   ],
  //   filterConfig: {
  //     indexForSearch: true,
  //     label: 'Tire size',
  //     group: 'secondary',
  //   },
  //   showConfig: {
  //     label: 'Tire size',
  //     isDetail: true,
  //   },
  //   saveConfig: {
  //     label: 'Tire size',
  //     placeholderMessage: 'Select an option…',
  //     isRequired: true,
  //     requiredMessage: 'You need to select a tire size.',
  //   },
  // },
  {
    key: 'marki',
    scope: 'public',
    schemaType: 'enum',
    enumOptions: [
      { option: '& other stories', label: '& Other Stories' },
      { option: '47 brand', label: '47 Brand' },
      { option: '8 other reasons', label: '8 Other Reasons' },
      { option: '9n1m sense', label: '9N1M SENSE' },
      { option: 'a star is born', label: 'A Star Is Born' },
      { option: 'a.kjaerbede', label: 'A.Kjaerbede' },
      { option: 'able active', label: 'Able Active' },
      { option: 'accessorize', label: 'Accessorize' },
      { option: 'adidas performance', label: 'adidas performance' },
      { option: 'adpt', label: 'ADPT' },
      { option: 'aeropostale', label: 'Aeropostale' },
      { option: 'afrm', label: 'AFRM' },
      { option: 'agon', label: 'Agon' },
      { option: 'aire', label: 'Aire' },
      { option: 'aj morgan', label: 'AJ Morgan' },
      { option: 'aldo', label: 'ALDO' },
      { option: 'aligne', label: 'Aligne' },
      { option: 'alma de ace', label: 'Alma De Ace' },
      { option: 'alpha industries', label: 'Alpha Industries' },
      { option: 'american stitch', label: 'American Stitch' },
      { option: 'amy jane london', label: 'Amy Jane London' },
      { option: 'amy lynn', label: 'Amy Lynn' },
      { option: 'anaya', label: 'Anaya' },
      { option: 'anaya maternity', label: 'Anaya Maternity' },
      { option: 'anaya petite', label: 'Anaya Petite' },
      { option: 'anaya plus', label: 'Anaya Plus' },
      { option: 'anaya tall', label: 'Anaya Tall' },
      { option: 'ann summers', label: 'Ann Summers' },
      { option: 'annorlunda', label: 'Annorlunda' },
      { option: 'another influence', label: 'Another Influence' },
      { option: 'another reason', label: 'Another Reason' },
      { option: 'aqaq', label: 'AQAQ' },
      { option: 'aria cove', label: 'Aria Cove' },
      { option: 'arizona love', label: 'Arizona Love' },
      { option: 'arket', label: 'Arket' },
      { option: 'armani exchange', label: 'Armani Exchange' },
      { option: 'artsac', label: 'Artsac' },
      { option: 'ashiana', label: 'Ashiana' },
      { option: 'asos design', label: 'ASOS DESIGN' },
      { option: 'asra', label: 'ASRA' },
      { option: 'asyou', label: 'AsYou' },
      { option: 'avant garde', label: 'AVANT GARDE' },
      { option: 'ax paris', label: 'AX Paris' },
      { option: 'ax paris plus', label: 'AX Paris Plus' },
      { option: 'azalea wang', label: 'AZALEA WANG' },
      { option: 'bad society club', label: 'BAD SOCIETY CLUB' },
      { option: 'baggu', label: 'Baggu' },
      { option: 'bailey rose', label: 'Bailey Rose' },
      { option: 'band of stars', label: 'Band of Stars' },
      { option: 'bando', label: 'Bando' },
      { option: 'barbour beacon', label: 'Barbour Beacon' },
      { option: 'barbour international', label: 'Barbour International' },
      { option: 'bardot', label: 'Bardot' },
      { option: 'barneys original petite', label: 'Barneys Original Petite' },
      { option: 'barneys original tall', label: 'Barneys Original Tall' },
      { option: 'barneys originals', label: 'Barneys Originals' },
      { option: 'barneys originals plus', label: 'Barneys Originals Plus' },
      { option: 'barry m', label: 'Barry M' },
      { option: 'base london', label: 'Base London' },
      { option: 'basic pleasure mode', label: 'Basic Pleasure Mode' },
      { option: 'batch1', label: 'Batch1' },
      { option: 'be mine', label: 'Be Mine' },
      { option: 'be mine wide fit', label: 'Be Mine Wide Fit' },
      { option: 'beauty works', label: 'Beauty Works' },
      { option: 'beauut', label: 'Beauut' },
      { option: 'bebo', label: 'BEBO' },
      { option: 'bebo wide fit', label: 'BEBO Wide Fit' },
      { option: 'bec & bridge', label: 'Bec & Bridge' },
      { option: 'becksondergaard', label: 'Becksondergaard' },
      { option: 'bellfield', label: 'Bellfield' },
      { option: 'ben sherman', label: 'Ben Sherman' },
      { option: 'bench', label: 'Bench' },
      { option: 'blank nyc', label: 'BLANK NYC' },
      { option: 'bloom and bay', label: 'Bloom and Bay' },
      { option: 'bluebella', label: 'Bluebella' },
      { option: 'blume bridal', label: 'Blume Bridal' },
      { option: 'boardmans', label: 'Boardmans' },
      { option: 'bohomoon', label: 'Bohomoon' },
      { option: 'bolongaro trevor', label: 'Bolongaro Trevor' },
      { option: 'bolongaro trevor sport', label: 'Bolongaro Trevor Sport' },
      { option: 'boohoo', label: 'Boohoo' },
      { option: 'boss', label: 'BOSS' },
      { option: 'boss bodywear', label: 'BOSS Bodywear' },
      { option: 'boss by hugo boss', label: 'BOSS by Hugo Boss' },
      { option: 'boss green', label: 'BOSS Green' },
      { option: 'boss orange', label: 'BOSS Orange' },
      { option: 'bote', label: 'Boté' },
      { option: 'boux avenue', label: 'Boux Avenue' },
      { option: 'brave soul', label: 'Brave Soul' },
      { option: 'bright swimwear', label: 'Bright Swimwear' },
      { option: 'bronx', label: 'Bronx' },
      { option: 'buffalo', label: 'Buffalo' },
      { option: 'burton', label: 'Burton' },
      { option: 'bye bra', label: 'Bye Bra' },
      { option: 'cabin max', label: 'Cabin Max' },
      { option: 'call it spring', label: 'Call it Spring' },
      { option: 'calvin klein golf', label: 'Calvin Klein Golf' },
      { option: 'calvin klein jeans', label: 'Calvin Klein Jeans' },
      { option: 'calvin klein jeans plus', label: 'Calvin Klein Jeans Plus' },
      { option: 'camper', label: 'Camper' },
      { option: 'candypants', label: 'Candypants' },
      { option: 'casio', label: 'Casio' },
      { option: 'cat footwear', label: 'Cat Footwear' },
      { option: 'catch', label: 'Catch' },
      { option: 'champion petite', label: 'Champion Petite' },
      { option: 'charles & keith', label: 'Charles & Keith' },
      { option: 'charlotte tilbury', label: 'Charlotte Tilbury' },
      { option: 'cheap monday', label: 'Cheap Monday' },
      { option: 'chelsea peers', label: 'Chelsea Peers' },
      { option: 'chelsea peers petite', label: 'Chelsea Peers Petite' },
      { option: 'chelsea peers tall', label: 'Chelsea Peers Tall' },
      { option: 'cherry beach', label: 'Cherry Beach' },
      { option: 'chi chi london', label: 'Chi Chi London' },
      { option: 'christin lars', label: 'Christin Lars' },
      { option: 'circus ny', label: 'Circus NY' },
      { option: 'clarks', label: 'Clarks' },
      { option: 'clarks originals', label: 'Clarks Originals' },
      { option: 'classics 77', label: 'Classics 77' },
      { option: 'claudia canova', label: 'Claudia Canova' },
      { option: 'closet london', label: 'Closet London' },
      { option: 'closet london maternity', label: 'Closet London Maternity' },
      { option: 'closet london petite', label: 'Closet London Petite' },
      { option: 'closet london plus', label: 'Closet London Plus' },
      { option: 'closet london tall', label: 'Closet London Tall' },
      { option: 'club l london', label: 'Club L London' },
      { option: 'coccinelle', label: 'Coccinelle' },
      { option: 'collective the label', label: 'Collective The Label' },
      { option: 'collective the label curve', label: 'Collective the Label Curve' },
      { option: 'collective the label petite', label: 'Collective The Label Petite' },
      { option: 'collusion', label: 'Collusion' },
      { option: 'columbia', label: 'Columbia' },
      { option: 'commando', label: 'Commando' },
      { option: 'coney island picnic', label: 'Coney Island Picnic' },
      { option: 'consigned', label: 'Consigned' },
      { option: 'cop copine', label: 'Cop Copine' },
      { option: 'cosmogonie', label: 'Cosmogonie' },
      { option: 'cotton:on', label: 'Cotton:On' },
      { option: 'crep protect', label: 'Crep Protect' },
      { option: 'crescent', label: 'Crescent' },
      { option: 'criminal damage', label: 'Criminal Damage' },
      { option: 'crocs', label: 'Crocs' },
      { option: 'crooked tongues', label: 'Crooked Tongues' },
      { option: 'curvy kate', label: 'Curvy Kate' },
      { option: 'daisy london', label: 'Daisy London' },
      { option: 'daisy street', label: 'Daisy Street' },
      { option: 'daisy street plus', label: 'Daisy Street Plus' },
      { option: 'damson madder', label: 'Damson Madder' },
      { option: 'dare 2b', label: 'Dare 2b' },
      { option: 'dark pink', label: 'Dark Pink' },
      { option: 'daska', label: 'Daska' },
      { option: 'day 6', label: 'DAY 6' },
      { option: 'denim project', label: 'Denim Project' },
      { option: 'designb london', label: 'DesignB London' },
      { option: 'designb london curve', label: 'DesignB London Curve' },
      { option: 'deus ex machina', label: 'Deus Ex Machina' },
      { option: 'devils advocate', label: "Devils Advocate" },
      { option: 'dickies', label: 'Dickies' },
      { option: 'diff eyewear', label: 'DIFF Eyewear' },
      { option: "dippin' daisy's", label: "Dippin' Daisy's" },
      { option: 'dkny', label: 'DKNY' },
      { option: 'dkny active', label: 'DKNY Active' },
      { option: 'dolce vita', label: 'Dolce Vita' },
      { option: "don't think twice", label: "Don't Think Twice" },
      { option: 'dorina', label: 'Dorina' },
      { option: 'dr denim', label: 'Dr Denim' },
      { option: 'dr denim petite', label: 'Dr Denim Petite' },
      { option: 'dr denim plus', label: 'Dr Denim Plus' },
      { option: 'dr denim tall', label: 'Dr Denim Tall' },
      { option: 'dr martens', label: 'Dr Martens' },
      { option: 'dream but do not sleep', label: 'Dream But Do Not Sleep' },
      { option: 'drycorn', label: 'Drycorn' },
      { option: 'dune london', label: 'Dune London' },
      { option: 'dune wide fit', label: 'Dune Wide Fit' },
      { option: 'e.l.f.', label: 'e.l.f.' },
      { option: 'ea7', label: 'EA7' },
      { option: 'easilocks', label: 'Easilocks' },
      { option: 'easy tiger', label: 'Easy Tiger' },
      { option: 'ed hardy', label: 'Ed Hardy' },
      { option: 'edikted', label: 'Edikted' },
      { option: 'edited', label: 'Edited' },
      { option: 'ego', label: 'EGO' },
      { option: 'ei8th hour', label: 'EI8TH HOUR' },
      { option: 'eivy', label: 'Eivy' },
      { option: 'element', label: 'Element' },
      { option: 'elle', label: 'Elle' },
      { option: 'ellesse', label: 'ellesse' },
      { option: 'elliatt', label: 'Elliatt' },
      { option: 'elsie & fred', label: 'Elsie & Fred' },
      { option: 'elvi', label: 'Elvi' },
      { option: 'emory park', label: 'Emory Park' },
      { option: 'emporio armani', label: 'Emporio Armani' },
      { option: 'en creme', label: 'En Crème' },
      { option: 'envii', label: 'Envii' },
      { option: 'esmee', label: 'Esmée' },
      { option: 'esmee curve', label: 'Esmee Curve' },
      { option: 'extro & vert', label: 'Extro & Vert' },
      { option: 'extro & vert petite', label: 'Extro & Vert Petite' },
      { option: 'extro & vert plus', label: 'Extro & Vert Plus' },
      { option: 'extro & vert tall', label: 'Extro & Vert Tall' },
      { option: 'faded future', label: 'FADED FUTURE' },
      { option: 'fae', label: 'FAE' },
      { option: 'farah', label: 'Farah' },
      { option: 'farai london', label: 'Farai London' },
      { option: 'fashion union', label: 'Fashion Union' },
      { option: 'fashion union maternity', label: 'Fashion Union Maternity' },
      { option: 'fashion union plus', label: 'Fashion Union Plus' },
      { option: 'fashionkilla', label: 'Fashionkilla' },
      { option: 'fashionkilla plus', label: 'Fashionkilla Plus' },
      { option: 'fat moose', label: 'Fat Moose' },
      { option: 'femme luxe', label: 'Femme Luxe' },
      { option: 'fenton', label: 'Fenton' },
      { option: 'figleaves', label: 'Figleaves' },
      { option: 'figleaves curve', label: 'Figleaves Curve' },
      { option: 'finding friday', label: 'Finding Friday' },
      { option: 'fiorucci', label: 'Fiorucci' },
      { option: 'fire & glory', label: 'Fire & Glory' },
      { option: 'first distraction', label: 'First Distraction' },
      { option: 'first distraction petite', label: 'First Distraction Petite' },
      { option: 'first distraction plus', label: 'First Distraction Plus' },
      { option: 'first distraction tall', label: 'First Distraction Tall' },
      { option: 'flook', label: 'Flook' },
      { option: 'flounce london', label: 'Flounce London' },
      { option: 'flounce london maternity', label: 'Flounce London Maternity' },
      { option: 'flounce london petite', label: 'Flounce London Petite' },
      { option: 'flounce london plus', label: 'Flounce London Plus' },
      { option: 'flounce london tall', label: 'Flounce London Tall' },
      { option: 'forever new', label: 'Forever New' },
      { option: 'forever new curve', label: 'Forever New Curve' },
      { option: 'forever new petite', label: 'Forever New Petite' },
      { option: 'forever u', label: 'Forever U' },
      { option: 'forever unique', label: 'Forever Unique' },
      { option: 'frankies bikinis', label: 'Frankies Bikinis' },
      { option: 'fred perry', label: 'Fred Perry' },
      { option: 'free people', label: 'Free People' },
      { option: 'free society', label: 'Free Society' },
      { option: 'freedom moses', label: 'Freedom Moses' },
      { option: 'french connection', label: 'French Connection' },
      { option: 'french connection mens', label: 'French Connection Mens' },
      { option: 'frock and frill', label: 'Frock and Frill' },
      { option: 'frock and frill tall', label: 'Frock and Frill Tall' },
      { option: 'frock and frill petite', label: 'Frock and Frill Petite' },
      { option: 'frock and frill plus', label: 'Frock and Frill Plus' },
      { option: 'furla', label: 'Furla' },
      { option: 'gant', label: 'Gant' },
      { option: 'gbemi', label: 'Gbemi' },
      { option: 'ghd', label: 'ghd' },
      { option: 'ghospell', label: 'Ghospell' },
      { option: 'gianni feraud', label: 'Gianni Feraud' },
      { option: 'gilli', label: 'Gilli' },
      { option: 'gilly hicks', label: 'Gilly Hicks' },
      { option: 'gipsy', label: 'Gipsy' },
      { option: 'girls crew', label: 'Girls Crew' },
      { option: 'girls on film', label: 'Girls on Film' },
      { option: 'glamorous', label: 'Glamorous' },
      { option: 'glamorous bloom', label: 'Glamorous Bloom' },
      { option: 'glamorous curve', label: 'Glamorous Curve' },
      { option: 'glamorous maternity', label: 'Glamorous Maternity' },
      { option: 'glamorous petite', label: 'Glamorous Petite' },
      { option: 'glamorous wide fit', label: 'Glamorous Wide Fit' },
      { option: 'go guy', label: 'Go Guy' },
      { option: 'goddiva', label: 'Goddiva' },
      { option: 'goldsboro', label: 'Goldsboro' },
      { option: 'good for nothing', label: 'Good For Nothing' },
      { option: 'good news', label: 'Good News' },
      { option: 'gossard', label: 'Gossard' },
      { option: 'gramicci', label: 'Gramicci' },
      { option: 'greentreat', label: 'Greentreat' },
      { option: 'grey hawk', label: 'Grey Hawk' },
      { option: 'g-star', label: 'G-Star' },
      { option: 'guess originals', label: 'Guess Originals' },
      { option: 'gym king', label: 'Gym King' },
      { option: 'h by hudson', label: 'H by Hudson' },
      { option: 'harry brown', label: 'Harry Brown' },
      { option: 'havaianas', label: 'Havaianas' },
      { option: 'heartbreak', label: 'Heartbreak' },
      { option: 'heartbreak petite', label: 'Heartbreak Petite' },
      { option: 'heartbreak plus', label: 'Heartbreak Plus' },
      { option: 'heartbreak tall', label: 'Heartbreak Tall' },
      { option: 'heathe', label: 'Heathe' },
      { option: 'heiress beverly hills', label: 'Heiress Beverly Hills' },
      { option: 'helene berman', label: 'Helene Berman' },
      { option: 'helly hansen', label: 'Helly Hansen' },
      { option: 'hera', label: 'Hera' },
      { option: 'heretic nine', label: 'Heretic Nine' },
      { option: 'herschel supply co', label: 'Herschel Supply Co' },
      { option: 'hiit', label: 'HIIT' },
      { option: 'honour', label: 'Honour' },
      { option: 'hope & ivy', label: 'Hope & Ivy' },
      { option: 'hope & ivy maternity', label: 'Hope & Ivy Maternity' },
      { option: 'hope & ivy plus', label: 'Hope & Ivy Plus' },
      { option: 'hotmilk', label: 'Hotmilk' },
      { option: 'hounour plus', label: 'Hounour Plus' },
      { option: 'house of holland', label: 'House of Holland' },
      { option: 'hoxton haus', label: 'Hoxton Haus' },
      { option: 'huf', label: 'HUF' },
      { option: 'hugo', label: 'HUGO' },
      { option: 'hugo blue', label: 'Hugo Blue' },
      { option: 'hugo boss', label: 'Hugo Boss' },
      { option: 'hugo red', label: 'Hugo Red' },
      { option: 'hummel', label: 'Hummel' },
      { option: 'hunkemoller', label: 'Hunkemoller' },
      { option: 'hunky trunks', label: 'Hunky Trunks' },
      { option: 'hunter', label: 'Hunter' },
      { option: 'hurley', label: 'Hurley' },
      { option: 'hvisk', label: 'HVISK' },
      { option: 'i heart revolution', label: 'I Heart Revolution' },
      { option: 'i saw it first', label: 'I Saw It First' },
      { option: 'i saw it first curve', label: 'I Saw It First Curve' },
      { option: 'i saw it first petite', label: 'I Saw It First Petite' },
      { option: 'icon brand', label: 'Icon Brand' },
      { option: 'iiqual', label: 'IIQUAL' },
      { option: 'iisla & bird', label: 'Iisla & Bird' },
      { option: 'il sarto', label: 'Il Sarto' },
      { option: 'il sarto curve', label: 'Il Sarto Curve' },
      { option: 'image gang', label: 'Image Gang' },
      { option: 'in the style', label: 'In The Style' },
      { option: 'in the style petite', label: 'In The Style Petite' },
      { option: 'in the style plus', label: 'In The Style Plus' },
      { option: 'in the style tall', label: 'In The Style Tall' },
      { option: 'in wear', label: 'In Wear' },
      { option: 'influence', label: 'Influence' },
      { option: 'influence maternity', label: 'Influence Maternity' },
      { option: 'influence petite', label: 'Influence Petite' },
      { option: 'influence plus', label: 'Influence Plus' },
      { option: 'influence tall', label: 'Influence Tall' },
      { option: 'inked by dani', label: 'INKED by Dani' },
      { option: 'ipanema', label: 'Ipanema' },
      { option: 'isla & bird', label: 'Isla & Bird' },
      { option: 'its now cool', label: 'Its Now Cool' },
      { option: 'ivory rose', label: 'Ivory Rose' },
      { option: 'ivory rose lingerie', label: 'Ivory Rose Lingerie' },
      { option: 'ixos', label: 'Ixos' },
      { option: 'jack wolfskin', label: 'Jack Wolfskin' },
      { option: 'jaded london', label: 'Jaded London' },
      { option: 'jaded rose', label: 'Jaded Rose' },
      { option: 'jaded rose maternity', label: 'Jaded Rose Maternity' },
      { option: 'jaded rose petite', label: 'Jaded Rose Petite' },
      { option: 'jaded rose plus', label: 'Jaded Rose Plus' },
      { option: 'jaded rose tall', label: 'Jaded Rose Tall' },
      { option: 'jarlo', label: 'Jarlo' },
      { option: 'jayley', label: 'Jayley' },
      { option: 'jdy', label: 'JDY' },
      { option: 'jdy petite', label: 'JDY Petite' },
      { option: 'jdy tall', label: 'JDY Tall' },
      { option: 'jeepers peepers', label: 'Jeepers Peepers' },
      { option: 'jeffrey campbell', label: 'Jeffrey Campbell' },
      { option: 'jewel jemila', label: 'Jewel Jemila' },
      { option: 'jj rebel', label: 'JJ Rebel' },
      { option: 'jjxx', label: 'JJXX' },
      { option: 'john zack', label: 'John Zack' },
      { option: 'john zack plus', label: 'John Zack Plus' },
      { option: 'john zack tall', label: 'John Zack Tall' },
      { option: 'jojoe', label: 'Jojoe' },
      { option: 'jordan', label: 'Jordan' },
      { option: 'juicy couture', label: 'Juicy Couture' },
      { option: 'just me', label: 'Just Me' },
      { option: 'kaiia', label: 'Kaiia' },
      { option: 'kanya london', label: 'Kanya London' },
      { option: 'karen millen', label: 'Karen Millen' },
      { option: 'karl kani', label: 'Karl Kani' },
      { option: 'karl lagerfeld', label: 'Karl Lagerfeld' },
      { option: 'kate spade', label: 'Kate Spade' },
      { option: 'kavu', label: 'KAVU' },
      { option: 'kayali', label: 'KAYALI' },
      { option: 'kbx', label: 'KBX' },
      { option: 'keen', label: 'Keen' },
      { option: 'kickers', label: 'Kickers' },
      { option: 'kingsley ryan', label: 'Kingsley Ryan' },
      { option: 'kingsley ryan curve', label: 'Kingsley Ryan Curve' },
      { option: 'kiss the sky', label: 'Kiss The Sky' },
      { option: 'kitsch', label: 'Kitsch' },
      { option: 'kiwi & co', label: 'Kiwi & Co' },
      { option: 'koi footwear', label: 'Koi Footwear' },
      { option: 'k-swiss', label: 'K-Swiss' },
      { option: 'kulani kinis', label: 'Kulani Kinis' },
      { option: 'kurt geiger london', label: 'Kurt Geiger London' },
      { option: 'kyo', label: 'KYO' },
      { option: 'labelrail', label: 'Labelrail' },
      { option: 'lace & beads', label: 'Lace & Beads' },
      { option: 'lace & beads petite', label: 'Lace & Beads Petite' },
      { option: 'lace & beads plus', label: 'Lace & Beads Plus' },
      { option: 'lambretta', label: 'Lambretta' },
      { option: 'lamoda', label: 'Lamoda' },
      { option: 'lashes of london', label: 'Lashes of London' },
      { option: 'lasula', label: 'Lasula' },
      { option: 'lauren by ralph lauren', label: 'LAUREN by RALPH LAUREN' },
      { option: 'lavish alice', label: 'Lavish Alice' },
      { option: 'lavish alice plus', label: 'Lavish Alice Plus' },
      { option: 'le breve', label: 'Le Breve' },
      { option: 'le coq sportif', label: 'Le Coq Sportif' },
      { option: 'le mini macaron', label: 'Le Mini Macaron' },
      { option: 'le monde gourmand', label: 'Le Monde Gourmand' },
      { option: 'le specs', label: 'Le Specs' },
      { option: 'lee', label: 'Lee' },
      { option: 'lee jeans', label: 'Lee Jeans' },
      { option: 'lee plus', label: 'Lee Plus' },
      { option: 'leg avenue', label: 'Leg Avenue' },
      { option: 'les girls les boys', label: 'Les Girls Les Boys' },
      { option: 'levi\'s', label: 'Levi\'s' },
      { option: 'levis skateboarding', label: 'LEVIS SKATEBOARDING' },
      { option: 'liars & lovers', label: 'Liars & Lovers' },
      { option: 'limit', label: 'Limit' },
      { option: 'lindex', label: 'Lindex' },
      { option: 'lioness', label: 'Lioness' },
      { option: 'liquor n poker', label: 'Liquor N Poker' },
      { option: 'liquorish', label: 'Liquorish' },
      { option: 'liquorish maternity', label: 'Liquorish Maternity' },
      { option: 'liquorish petite', label: 'Liquorish Petite' },
      { option: 'liquorish plus', label: 'Liquorish Plus' },
      { option: 'liquorish tall', label: 'Liquorish Tall' },
      { option: 'little mistress', label: 'Little Mistress' },
      { option: 'little mistress maternity', label: 'Little Mistress Maternity' },
      { option: 'little mistress plus', label: 'Little Mistress Plus' },
      { option: 'little mistress tall', label: 'Little Mistress Tall' },
      { option: 'liu jo', label: 'Liu Jo' },
      { option: 'lola may', label: 'Lola May' },
      { option: 'lola may curve', label: 'Lola May Curve' },
      { option: 'lola may petite', label: 'LOLA MAY PETITE' },
      { option: 'lola may tall', label: 'LOLA MAY TALL' },
      { option: 'london rebel', label: 'London Rebel' },
      { option: 'london rebel leather', label: 'London Rebel Leather' },
      { option: 'london rebel leather wide fit', label: 'London Rebel Leather Wide Fit' },
      { option: 'london rebel wide fit', label: 'London Rebel Wide Fit' },
      { option: 'london rebel x', label: 'London Rebel X' },
      { option: 'loreal elvive', label: 'L\'Oreal Elvive' },
      { option: 'lost ink', label: 'Lost Ink' },
      { option: 'lost souls', label: 'LOST SOULS' },
      { option: 'lottie and holly', label: 'Lottie And Holly' },
      { option: 'loungeable', label: 'Loungeable' },
      { option: 'loungeable petite', label: 'Loungeable Petite' },
      { option: 'loungeable tall', label: 'Loungeable Tall' },
      { option: 'love & other things', label: 'Love & Other Things' },
      { option: 'love moschino', label: 'Love Moschino' },
      { option: 'love triangle', label: 'Love Triangle' },
      { option: 'lovedrobe', label: 'Lovedrobe' },
      { option: 'lovedrobe luxe plus', label: 'Lovedrobe Luxe Plus' },
      { option: 'lovers fc', label: 'Lovers FC' },
      { option: 'lovisa', label: 'Lovisa' },
      { option: 'loyalty & faith', label: 'Loyalty & Faith' },
      { option: 'luke', label: 'Luke' },
      { option: 'luna', label: 'Luna' },
      { option: 'luxe palm', label: 'Luxe Palm' },
      { option: 'lyle & scott', label: 'Lyle & Scott' },
      { option: 'lyle & scott vintage', label: 'Lyle & Scott Vintage' },
      { option: 'm lounge', label: 'M Lounge' },
      { option: 'm lounge curve', label: 'M Lounge Curve' },
      { option: 'mad beauty', label: 'M.A.D Beauty' },
      { option: 'mac', label: 'MAC' },
      { option: 'madden girl', label: 'Madden Girl' },
      { option: 'madein', label: 'Madein.' },
      { option: 'madewell', label: 'Madewell' },
      { option: 'magic', label: 'Magic' },
      { option: 'maids to measure', label: 'Maids to Measure' },
      { option: 'maison scotch', label: 'Maison Scotch' },
      { option: 'mama.licious', label: 'Mama.licious' },
      { option: 'mamalicious', label: 'MAMALICIOUS' },
      { option: 'marbek', label: 'Marbek' },
      { option: 'marc b', label: 'Marc B' },
      { option: 'marc jacobs', label: 'Marc Jacobs' },
      { option: 'marella', label: 'Marella' },
      { option: 'marshall artist', label: 'Marshall Artist' },
      { option: 'massimo dutti', label: 'Massimo Dutti' },
      { option: 'matt & nat', label: 'matt & nat' },
      { option: 'max & co', label: 'Max & Co' },
      { option: 'maya', label: 'Maya' },
      { option: 'maya maternity', label: 'Maya Maternity' },
      { option: 'maya plus', label: 'Maya Plus' },
      { option: 'maya tall', label: 'Maya Tall' },
      { option: 'me n em', label: 'ME+EM' },
      { option: 'melissa', label: 'Melissa' },
      { option: 'mennace', label: 'Mennace' },
      { option: 'messina hembry clothing ltd', label: 'Messina Hembry Clothing Ltd' },
      { option: 'messy weekend', label: 'Messy Weekend' },
      { option: 'mim', label: 'MIM' },
      { option: 'minga', label: 'Minga' },
      { option: 'miss selfridge', label: 'Miss Selfridge' },
      { option: 'miss selfridge petite', label: 'Miss Selfridge Petite' },
      { option: 'miss sixty', label: 'Miss Sixty' },
      { option: 'missguided maternity', label: 'Missguided Maternity' },
      { option: 'missguided petite', label: 'Missguided Petite' },
      { option: 'missguided plus', label: 'Missguided Plus' },
      { option: 'missguided tall', label: 'Missguided Tall' },
      { option: 'missyempire', label: 'Missyempire' },
      { option: 'moda minx', label: 'Moda Minx' },
      { option: 'modibodi', label: 'ModiBodi' },
      { option: 'monki', label: 'Monki' },
      { option: 'moon boot', label: 'Moon Boot' },
      { option: 'moon river', label: 'Moon River' },
      { option: 'morgan', label: 'Morgan' },
      { option: 'moschino', label: 'Moschino' },
      { option: 'motel', label: 'Motel' },
      { option: 'murci', label: 'Murci' },
      { option: 'muubaa', label: 'Muubaa' },
      { option: 'my accessories', label: 'My Accessories' },
      { option: 'my accessories curve', label: 'My Accessories Curve' },
      { option: 'naanaa', label: 'NaaNaa' },
      { option: 'naanaa petite', label: 'NaaNaa Petite' },
      { option: 'naanaa plus', label: 'NaaNaa Plus' },
      { option: 'naanaa tall', label: 'NaaNaa Tall' },
      { option: 'na-kd', label: 'NA-KD' },
      { option: 'naked wardrobe', label: 'Naked Wardrobe' },
      { option: 'naked wardrobe maternity', label: 'Naked Wardrobe Maternity' },
      { option: 'napapijri', label: 'Napapijri' },
      { option: 'narrated', label: 'Narrated' },
      { option: 'native youth', label: 'Native Youth' },
      { option: 'native youth plus', label: 'Native Youth Plus' },
      { option: 'nautica competition', label: 'Nautica Competition' },
      { option: 'neck on the line', label: 'Neck On The Line' },
      { option: 'neon rose', label: 'Neon Rose' },
      { option: 'neon rose plus', label: 'Neon Rose Plus' },
      { option: 'nesavaali', label: 'Nesavaali' },
      { option: 'never fully dressed', label: 'Never Fully Dressed' },
      { option: 'never fully dressed plus', label: 'Never Fully Dressed Plus' },
      { option: 'new era', label: 'New Era' },
      { option: 'new girl order', label: 'New Girl Order' },
      { option: 'new girl order curve', label: 'New Girl Order Curve' },
      { option: 'new girl order petite', label: 'New Girl Order Petite' },
      { option: 'new look', label: 'New Look' },
      { option: 'new look maternity', label: 'New Look Maternity' },
      { option: 'new look petite', label: 'New Look Petite' },
      { option: 'new look plus', label: 'New Look Plus' },
      { option: 'new look tall', label: 'New Look Tall' },
      { option: 'new look wide fit', label: 'New Look Wide Fit' },
      { option: 'new love club', label: 'New Love Club' },
      { option: 'new love club plus', label: 'New Love Club Plus' },
      { option: 'nicce', label: 'Nicce' },
      { option: 'night', label: 'NIGHT' },
      { option: 'night addict', label: 'Night Addict' },
      { option: 'night addict plus', label: 'Night Addict Plus' },
      { option: 'niihai', label: 'Niihai' },
      { option: 'nike basketball', label: 'Nike Basketball' },
      { option: 'nike football', label: 'Nike Football' },
      { option: 'nike golf', label: 'Nike Golf' },
      { option: 'nike running', label: 'Nike Running' },
      { option: 'nike sb', label: 'Nike SB' },
      { option: 'nike swimming', label: 'Nike Swimming' },
      { option: 'nike training', label: 'Nike Training' },
      { option: 'noak', label: 'Noak' },
      { option: 'nobodys child maternity', label: "Nobody's Child Maternity" },
      { option: 'nobodys child petite', label: "Nobody's Child Petite" },
      { option: 'nobodys child', label: "Nobody's Child" },
      { option: 'nobodys child plus', label: "Nobody's Child Plus" },
      { option: 'noisy may', label: 'Noisy May' },
      { option: 'noisy may curve', label: 'Noisy May Curve' },
      { option: 'noisy may petite', label: 'Noisy May Petite' },
      { option: 'noisy may tall', label: 'Noisy May Tall' },
      { option: 'nokwol', label: 'Nokwol' },
      { option: 'nytt', label: 'NYTT' },
      { option: "oakley", "label": "Oakley" },
      { option: "oasis", "label": "Oasis" },
      { option: "o bаg", "label": "O bаg" },
      { option: "obey", "label": "Obey" },
      { option: "object", "label": "Object" },
      { option: "object tall", "label": "Object Tall" },
      { option: "off the hook", "label": "Off The Hook" },
      { option: "office", "label": "Office" },
      { option: "old but gold vintage", "label": "Old But Gold Vintage" },
      { option: "omnes", "label": "Omnes" },
      { option: "on running", "label": "On Running" },
      { option: "one above another", "label": "One Above Another" },
      { option: "o'neill", "label": "O'Neill" },
      { option: "onia", "label": "Onia" },
      { option: "only", "label": "ONLY" },
      { option: "only & sons", "label": "ONLY & SONS" },
      { option: "only curve", "label": "Only Curve" },
      { option: "only maternity", "label": "Only Maternity" },
      { option: "only petite", "label": "Only Petite" },
      { option: "only play", "label": "Only Play" },
      { option: "only tall", "label": "Only Tall" },
      { option: "oosc", "label": "OOSC" },
      { option: "orelia", "label": "Orelia" },
      { option: "original penguin", "label": "Original Penguin" },
      { option: "orrsum", "label": "Orrsum" },
      { option: "outrageous fortune", "label": "Outrageous Fortune" },
      { option: "ow collection", "label": "OW Collection" },
      { option: "ow intimates", "label": "OW Intimates" },
      { option: "pajar", "label": "Pajar" },
      { option: "palladium", "label": "Palladium" },
      { option: "parallel lines", "label": "Parallel Lines" },
      { option: "parisian", "label": "Parisian" },
      { option: "parisian petite", "label": "Parisian Petite" },
      { option: "parisian plus", "label": "Parisian Plus" },
      { option: "parisian tall", "label": "Parisian Tall" },
      { option: "parlez", "label": "Parlez" },
      { option: "pasq", "label": "PASQ" },
      { option: "paul costelloe", "label": "Paul Costelloe" },
      { option: "paul smith", "label": "Paul Smith" },
      { option: "peek & beau", "label": "Peek & Beau" },
      { option: "peek & beau curve", "label": "Peek & Beau Curve" },
      { option: "people tree", "label": "People Tree" },
      { option: "pepe jeans", "label": "Pepe Jeans" },
      { option: "pepper mayo", "label": "Pepper Mayo" },
      { option: "peppermayo", "label": "Peppermayo" },
      { option: "persol", "label": "Persol" },
      { option: "petit moments", "label": "Petit Moments" },
      { option: "pieces", "label": "Pieces" },
      { option: "pieces maternity", "label": "Pieces Maternity" },
      { option: "pieces petite", "label": "Pieces Petite" },
      { option: "pieces plus", "label": "Pieces Plus" },
      { option: "pieces tall", "label": "Pieces Tall" },
      { option: "pimkie", "label": "Pimkie" },
      { option: "pink soda", "label": "Pink Soda" },
      { option: "planks", "label": "Planks" },
      { option: "playful promises", "label": "Playful Promises" },
      { option: "polo ralph lauren", "label": "Polo Ralph Lauren" },
      { option: "pour moi", "label": "Pour Moi" },
      { option: "pretty green", "label": "Pretty Green" },
      { option: "pretty lavish", "label": "Pretty Lavish" },
      { option: "pretty lavish curve", "label": "Pretty Lavish Curve" },
      { option: "pretty polly", "label": "Pretty Polly" },
      { option: "prince", "label": "Prince" },
      { option: "prnt", "label": "PRNT" },
      { option: "prohibited", "label": "Prohibited" },
      { option: "protest", "label": "Protest" },
      { option: "ps paul smith", "label": "PS Paul Smith" },
      { option: "public desire", "label": "Public Desire" },
      { option: "public desire curve", "label": "Public Desire Curve" },
      { option: "public desire wide fit", "label": "Public Desire Wide Fit" },
      { option: "pull&bear", "label": "Pull&Bear" },
      { option: "pull&bear tall", "label": "Pull&Bear Tall" },
      { option: "puma golf", "label": "Puma Golf" },
      { option: "qed london", "label": "QED London" },
      { option: "qed london petite", "label": "QED London Petite" },
      { option: "qed london plus", "label": "QED London Plus" },
      { option: "qed london tall", "label": "QED London Tall" },
      { option: "quay australia", "label": "Quay Australia" },
      { option: "quiksilver", "label": "Quiksilver" },
      { option: "qupid", "label": "QUPID" },
      { option: "résumé", "label": "Résumé" },
      { option: "rachel jackson", "label": "Rachel Jackson" },
      { option: "raga", "label": "Raga" },
      { option: "raid", "label": "Raid" },
      { option: "raid wide fit", "label": "Raid Wide Fit" },
      { option: "rains", "label": "Rains" },
      { option: "ralph", "label": "Ralph" },
      { option: "ralph lauren", "label": "Ralph Lauren" },
      { option: "rare", "label": "Rare" },
      { option: "ray-ban", "label": "Ray-Ban" },
      { option: "rebellious fashion", "label": "Rebellious Fashion" },
      { option: "reclaimed vintage", "label": "Reclaimed Vintage" },
      { option: "red tape", "label": "Red Tape" },
      { option: "reef", "label": "Reef" },
      { option: "regatta", "label": "Regatta" },
      { option: "religion", "label": "Religion" },
      { option: "renee studio", "label": "Renee Studio" },
      { option: "replay", "label": "Replay" },
      { option: "revolution", "label": "Revolution" },
      { option: "revolution hair", "label": "Revolution Hair" },
      { option: "revolution pro", "label": "Revolution Pro" },
      { option: "revolution skincare", "label": "Revolution Skincare" },
      { option: "rhythm", "label": "Rhythm" },
      { option: "rimmel london", "label": "Rimmel London" },
      { option: "rip n dip", "label": "Rip N Dip" },
      { option: "ripcurl", "label": "Ripcurl" },
      { option: "rituals", "label": "Rituals" },
      { option: "river island", "label": "River Island" },
      { option: "river island fuller bust", "label": "River Island Fuller Bust" },
      { option: "river island maternity", "label": "River Island Maternity" },
      { option: "river island petite", "label": "River Island Petite" },
      { option: "river island plus", "label": "River Island Plus" },
      { option: "river island tall", "label": "River Island Tall" },
      { option: "rocketdog", "label": "Rocketdog" },
      { option: "rule london", "label": "Rule London" },
      { option: "russell athletic", "label": "Russell Athletic" },
      { option: "rvca", "label": "RVCA" },
      { option: "saint genies", "label": "Saint Genies" },
      { option: "saint genies plus", "label": "Saint Genies Plus" },
      { option: "salomon", "label": "Salomon" },
      { option: "santa cruz", "label": "Santa Cruz" },
      { option: "santa cruz plus", "label": "Santa Cruz Plus" },
      { option: "saucony", "label": "Saucony" },
      { option: "saye", "label": "Saye" },
      { option: "scalpers", "label": "Scalpers" },
      { option: "scandale Ã©co-lingerie", "label": "Scandale Éco-lingerie" },
      { option: "scantilly", "label": "Scantilly" },
      { option: "Scotch n Soda", "label": "Scotch & Soda" },
      { option: "schuh", "label": "Schuh" },
      { option: "sean john", "label": "Sean John" },
      { option: "sekonda", "label": "Sekonda" },
      { option: "selected", "label": "Selected" },
      { option: "selected homme", "label": "Selected Homme" },
      { option: "seol + gold", "label": "Seol + Gold" },
      { option: "seqwl", "label": "SEQWL" },
      { option: "seqwl wide fit", "label": "SEQWL Wide Fit" },
      { option: "serge denimes", "label": "Serge DeNimes" },
      { option: "sergio tacchini", "label": "Sergio Tacchini" },
      { option: "sheepskin by totes", "label": "Sheepskin by Totes" },
      { option: "shelby & sons", "label": "Shelby & Sons" },
      { option: "shellys london", "label": "Shellys London" },
      { option: "shock absorber", "label": "Shock Absorber" },
      { option: "signature 8", "label": "Signature 8" },
      { option: "siksilk", "label": "SikSilk" },
      { option: "simmi clothing", "label": "Simmi Clothing" },
      { option: "simmi london plus", "label": "Simmi London Plus" },
      { option: "simmi shoes", "label": "SIMMI Shoes" },
      { option: "simmi wide fit", "label": "Simmi Wide Fit" },
      { option: "simply be", "label": "Simply Be" },
      { option: "simply be wide fit", "label": "Simply Be Wide Fit" },
      { option: "sister jane", "label": "sister jane" },
      { option: "sister jane plus", "label": "Sister Jane Plus" },
      { option: "sisters of the tribe", "label": "Sisters of the Tribe" },
      { option: "six stories", "label": "Six Stories" },
      { option: "sixth june", "label": "Sixth June" },
      { option: "sixth june plus", "label": "Sixth June Plus" },
      { option: "skinnydip", "label": "Skinnydip" },
      { option: "skylar rose", "label": "Skylar Rose" },
      { option: "sloggi", "label": "Sloggi" },
      { option: "smith and canova", "label": "Smith And Canova" }, 
      { option: "sndys", "label": "SNDYS" },
      { option: "something new", "label": "Something New" },
      { option: "something new curve", "label": "Something New Curve" },
      { option: "sorel", "label": "Sorel" },
      { option: "soul star", "label": "Soul Star" },
      { option: "south beach", "label": "South Beach" },
      { option: "south beach curve", "label": "South Beach Curve" },
      { option: "south beach plus", "label": "South Beach Plus" },
      { option: "spanx", "label": "Spanx" },
      { option: "speedo", "label": "Speedo" },
      { option: "spitfire", "label": "Spitfire" },
      { option: "stan ray", "label": "Stan Ray" },
      { option: "starlet", "label": "Starlet" },
      { option: "starlet plus", "label": "Starlet Plus" },
      { option: "starry eyed", "label": "Starry Eyed" },
      { option: "steve madden", "label": "Steve Madden" },
      { option: 'staud', label: 'Staud' },
      { option: "stradivarius", "label": "Stradivarius" },
      { option: "street collective", "label": "Street Collective" },
      { option: "style cheat", "label": "Style Cheat" },
      { option: "stylestalker", "label": "Stylestalker" },
      { option: "sui ava", "label": "Sui Ava" },
      { option: "sunde", "label": "Sunde" },
      { option: "sunseeker", "label": "Sunseeker" },
      { option: "superdry", "label": "Superdry" },
      { option: "superga", "label": "Superga" },
      { option: "svn x", "label": "SVNX" },
      { option: "swarovski", "label": "Swarovski" },
      { option: "swim society", "label": "Swim Society" },
      { option: "tala", "label": "Tala" },
      { option: "tammy girl", "label": "Tammy Girl" },
      { option: "tammy girl curve", "label": "Tammy Girl Curve" },
      { option: "tealer", "label": "Tealer" },
      { option: "teva", "label": "Teva" },
      { option: "tfnc", "label": "TFNC" },
      { option: "tfnc maternity", "label": "TFNC Maternity" },
      { option: "tfnc petite", "label": "TFNC Petite" },
      { option: "tfnc plus", "label": "TFNC Plus" },
      { option: "tfnc tall", "label": "TFNC Tall" },
      { option: "the beauty crop", "label": "The Beauty Crop" },
      { option: "the couture club", "label": "The Couture Club" },
      { option: "the frolic", "label": "The Frolic" },
      { option: "the frolic maternity", "label": "The Frolic Maternity" },
      { option: "the frolic plus", "label": "The Frolic Plus" },
      { option: "the hundreds", "label": "The Hundreds" },
      { option: "the inkey list", "label": "THE INKEY LIST" },
      { option: "the kript", "label": "The Kript" },
      { option: "the o dolls collection", "label": "The O Dolls Collection" },
      { option: "the ragged priest", "label": "The Ragged Priest" },
      { option: "the status syndicate", "label": "The Status Syndicate" },
      { option: "the wellness project", "label": "The Wellness Project" },
      { option: "thinx", "label": "Thinx" },
      { option: "this girl i know", "label": "This Girl I Know" },
      { option: "thomas crick", "label": "Thomas Crick" },
      { option: "thomas crick wide fit", "label": "Thomas Crick Wide Fit" },
      { option: "threadbare", "label": "Threadbare" },
      { option: "tommy jeans", "label": "Tommy Jeans" },
      { option: "toms", "label": "Toms" },
      { option: "tony bianco", "label": "Tony Bianco" },
      { option: "topman", "label": "Topman" },
      { option: "topshop", "label": "Topshop" },
      { option: "topshop curve", "label": "Topshop Curve" },
      { option: "topshop hourglass", "label": "Topshop Hourglass" },
      { option: "topshop maternity", "label": "Topshop Maternity" },
      { option: "topshop petite", "label": "Topshop Petite" },
      { option: "topshop tall", "label": "Topshop Tall" },
      { option: "totes", "label": "Totes" },
      { option: "trendyol", "label": "TRENDYOL" },
      { option: "trendyol plus", "label": "Trendyol Plus" },
      { option: "true decadence", "label": "True Decadence" },
      { option: "true religion", "label": "True Religion" },
      { option: "true violet", "label": "True Violet" },
      { option: "true violet plus", "label": "True Violet Plus" },
      { option: "truffle collection", "label": "Truffle Collection" },
      { option: "tutti rouge", "label": "Tutti Rouge" },
      { option: "twiin", "label": "Twiin" },
      { option: "twisted tailor", "label": "Twisted Tailor" },
      { option: "twisted wunder", "label": "Twisted Wunder" },
      { option: "twisted wunder maternity", "label": "Twisted Wunder Maternity" },
      { option: "twisted wunder plus", "label": "Twisted Wunder Plus" },
      { option: "typo", "label": "TYPO" },
      { option: "ueen bee maternity", "label": "Ueen Bee Maternity" },
      { option: "ugg", "label": "UGG" },
      { option: "umbro", "label": "Umbro" },
      { option: "under armour", "label": "Under Armour" },
      { option: "unique21", "label": "UNIQUE21" },
      { option: "unique21 hero", "label": "UNIQUE21 Hero" },
      { option: "unique21 petite", "label": "Unique21 Petite" },
      { option: "unique21 tall", "label": "Unique21 Tall" },
      { option: "unreal fur", "label": "Unreal Fur" },
      { option: "urban bliss", "label": "Urban Bliss" },
      { option: "urban bliss maternity", "label": "Urban Bliss Maternity" },
      { option: "urban classics", "label": "Urban Classics" },
      { option: "urban code petite", "label": "Urban Code Petite" },
      { option: "urban code tall", "label": "Urban Code Tall" },
      { option: "urban decay", "label": "Urban Decay" },
      { option: "urban revivo", "label": "Urban Revivo" },
      { option: "urban threads", "label": "Urban Threads" },
      { option: "urban threads curve", "label": "Urban Threads Curve" },
      { option: "urban threads petite", "label": "Urban Threads Petite" },
      { option: "urban threads tall", "label": "Urban Threads Tall" },
      { option: "urbancode", "label": "Urbancode" },
      { option: "urbancode curve", "label": "Urbancode Curve" },
      { option: "vai21", "label": "VAI21" },
      { option: "varley", "label": "Varley" },
      { option: "veja", "label": "VEJA" },
      { option: "vera wang", "label": "Vera Wang" },
      { option: "vero moda", "label": "Vero Moda" },
      { option: "vero moda curve", "label": "Vero Moda Curve" },
      { option: "vero moda maternity", "label": "Vero Moda Maternity" },
      { option: "vero moda petite", "label": "Vero Moda Petite" },
      { option: "vero moda tall", "label": "Vero Moda Tall" },
      { option: "versace", "label": "Versace" },
      { option: "versace jeans couture", "label": "Versace Jeans Couture" },
      { option: "vesper", "label": "Vesper" },
      { option: "vesper maternity", "label": "Vesper Maternity" },
      { option: "vesper petite", "label": "Vesper Petite" },
      { option: "vesper plus", "label": "Vesper Plus" },
      { option: "vesper tall", "label": "Vesper Tall" },
      { option: "viggo", "label": "Viggo" },
      { option: "vila", "label": "Vila" },
      { option: "vila curve", "label": "Vila Curve" },
      { option: "vila petite", "label": "Vila Petite" },
      { option: "vintage supply", "label": "Vintage Supply" },
      { option: "violet romance", "label": "VIOLET ROMANCE" },
      { option: "violet romance curve", "label": "Violet Romance Curve" },
      { option: "violet romance maternity", "label": "Violet Romance Maternity" },
      { option: "violet romance petite", "label": "Violet Romance Petite" },
      { option: "violet romance tall", "label": "Violet Romance Tall" },
      { option: "virgos lounge", "label": "Virgos Lounge" },
      { option: "vl the label", "label": "VL the Label" },
      { option: "vogue", "label": "Vogue" },
      { option: "volcom", "label": "Volcom" },
      { option: "von dutch", "label": "Von Dutch" },
      { option: "vrg grl", "label": "Vrg Grl" },
      { option: "walk london", "label": "WALK LONDON" },
      { option: "waven", "label": "Waven" },
      { option: "wavey", "label": "WAVEY" },
      { option: "we are we wear", "label": "We Are We Wear" },
      { option: "we are we wear fuller bust", "label": "We Are We Wear Fuller Bust" },
      { option: "we the free by free people", "label": "We The Free by Free People" },
      { option: "wednesday's girl", "label": "Wednesday's Girl" },
      { option: "wednesday's girl curve", "label": "Wednesday's Girl Curve" },
      { option: "wednesday's girl maternity", "label": "Wednesday's Girl Maternity" },
      { option: "weekday", "label": "Weekday" },
      { option: "wesc", "label": "WESC" },
      { option: "wftw", "label": "WFTW" },
      { option: "whistles", "label": "Whistles" },
      { option: "whistles petite", "label": "Whistles Petite" },
      { option: "wild lovers", "label": "Wild Lovers" },
      { option: "wolf & whistle", "label": "Wolf & Whistle" },
      { option: "wolf & whistle curve", "label": "Wolf & Whistle Curve" },
      { option: "women secret", "label": "Womensecret" },
      { option: "wonderbra", "label": "Wonderbra" },
      { option: "wrangler", "label": "Wrangler" },
      { option: "wrangler plus", "label": "Wrangler Plus" },
      { option: "yas", "label": "YAS" },
      { option: "yas petite", "label": "YAS Petite" },
      { option: "yas tall", "label": "Yas Tall" },
      { option: "yaura", "label": "Yaura" },
      { option: "yours", "label": "Yours" },
      { option: "z_code_z", "label": "Z_Code_Z" },
      { option: "zemeta", "label": "Zemeta" },
      { option: "zulu & zephyr", "label": "Zulu & Zephyr" },
    ],
    filterConfig: {
      indexForSearch: true,
      label: 'Марки',
      group: 'secondary',
    },
    showConfig: {
      label: 'Марки',
      isDetail: true,
    },
    saveConfig: {
      label: 'Марки',
      placeholderMessage: 'Селектирай марка…',
      isRequired: true,
      requiredMessage: 'Трябва да изберете марка.',
    },
  },
  {
    key: 'dizaierski_marki',
    scope: 'public',
    schemaType: 'enum',
    enumOptions: [
      { option: '7 for all mankind', label: '7 For All Mankind' }, 
      { option: 'a.p.c.', label: 'A.P.C.' }, 
      { option: 'aimé leon dore', label: 'Aimé Leon Dore' }, 
      { option: 'alberta ferretti', label: 'Alberta Ferretti' }, 
      { option: 'alexander terekhov', label: 'Alexander Terekhov' }, 
      { option: 'alexander wang', label: 'Alexander Wang' }, 
      { option: 'alexis mabille', label: 'Alexis Mabille' }, 
      { option: 'altuzarra', label: 'Altuzarra' }, 
      { option: 'ami paris', label: 'Ami Paris' },
      { option: 'anine bing', label: 'Anine Bing' }, 
      { option: 'ann demeulemeester', label: 'Ann Demeulemeester' }, 
      { option: 'aquascutum', label: 'Aquascutum' }, 
      { option: 'armani', label: 'Armani' }, 
      { option: 'aspesi', label: 'Aspesi' }, 
      { option: 'balenciaga couture', label: 'Balenciaga Couture' }, 
      { option: 'barbara bui', label: 'Barbara Bui' }, 
      { option: 'barbour', label: 'Barbour' }, 
      { option: 'birkin bag', label: 'Birkin bag' }, 
      { option: 'boglioli', label: 'Boglioli' }, 
      { option: 'boucheron', label: 'Boucheron' }, 
      { option: 'braccialini', label: 'Braccialini' },
      { option: 'brioni', label: 'Brioni' }, 
      { option: 'brunello cucinelli', label: 'Brunello Cucinelli' }, 
      { option: 'bottega veneta', label: 'Bottega Veneta' }, 
      { option: 'buccellati', label: 'Buccellati' }, 
      { option: 'bulgari', label: 'Bulgari' }, 
      { option: 'burberry', label: 'Burberry' }, 
      { option: 'canali', label: 'Canali' }, 
      { option: 'carolina herrera', label: 'Carolina Herrera' }, 
      { option: 'cartier', label: 'Cartier' }, 
      { option: 'carven', label: 'Carven' }, 
      { option: 'celine', label: 'Céline' }, 
      { option: 'chanel haute couture', label: 'Chanel Haute Couture' }, 
      { option: 'chanel joaillerie', label: 'Chanel Joaillerie' }, 
      { option: 'chaumet', label: 'Chaumet' },
      { option: 'chloe', label: 'Chloé' }, 
      { option: 'chopard', label: 'Chopard' }, 
      { option: 'christophe lemaire', label: 'Christophe Lemaire' }, 
      { option: 'christopher kane', label: 'Christopher Kane' }, 
      { option: 'coach', label: 'Coach' }, 
      { option: 'comme des garçons', label: 'Comme des Garçons' }, 
      { option: 'comme des garçons shirt', label: 'Comme des Garçons Shirt' }, 
      { option: 'corneliani', label: 'Corneliani' }, 
      { option: 'current/elliott', label: 'Current/Elliott' }, 
      { option: 'de beers', label: 'De Beers' }, 
      { option: 'delpozo', label: 'Delpozo' }, 
      { option: 'diesel black gold', label: 'Diesel Black Gold' },
      { option: 'dior', label: 'Dior' }, 
      { option: 'dior haute couture', label: 'Dior Haute Couture' }, 
      { option: 'dior joaillerie', label: 'Dior Joaillerie' }, 
      { option: 'dries van noten', label: 'Dries Van Noten' }, 
      { option: 'dundas', label: 'Dundas' }, 
      { option: 'elie saab', label: 'Elie Saab' }, 
      { option: 'emanuel ungaro', label: 'Emanuel Ungaro' }, 
      { option: 'emilio pucci', label: 'Emilio Pucci' }, 
      { option: 'erdem', label: 'Erdem' }, 
      { option: 'ermenegildo zegna', label: 'Ermenegildo Zegna' }, 
      { option: 'etro', label: 'Etro' }, 
      { option: 'fausto puglisi', label: 'Fausto Puglisi' }, 
      { option: 'fear of god', label: 'Fear of God' }, 
      { option: 'fendi couture', label: 'Fendi Couture' }, 
      { option: 'filippa k', label: 'Filippa K' }, 
      { option: 'frame denim', label: 'Frame Denim' }, 
      { option: 'furs by yves salomon', label: 'Furs by Yves Salomon' }, 
      { option: 'gabriela hearst', label: 'Gabriela Hearst' }, 
      { option: 'ganni', label: 'Ganni' },
      { option: 'gaurav gupta', label: 'Gaurav Gupta' }, 
      { option: 'giambattista valli', label: 'Giambattista Valli' }, 
      { option: 'gianvito rossi', label: 'Gianvito Rossi' }, 
      { option: 'gieves & hawkes', label: 'Gieves & Hawkes' }, 
      { option: 'givenchy', label: 'Givenchy' }, 
      { option: 'graff', label: 'Graff' }, 
      { option: 'gucci', label: 'Gucci' }, 
      { option: 'gucci fine jewelry', label: 'Gucci Fine Jewelry' }, 
      { option: 'hackett london', label: 'Hackett London' }, 
      { option: 'halston', label: 'Halston' }, 
      { option: 'harry winston', label: 'Harry Winston' }, 
      { option: 'helmut lang', label: 'Helmut Lang' }, 
      { option: 'hermes', label: 'Hermès' }, 
      { option: 'hunter', label: 'Hunter' }, 
      { option: 'hussein chalayan', label: 'Hussein Chalayan' }, 
      { option: 'imane ayissi', label: 'Imane Ayissi' }, 
      { option: 'issey miyake', label: 'Issey Miyake' }, 
      { option: 'j brand', label: 'J Brand' }, 
      { option: 'jean paul gaultier couture', label: 'Jean Paul Gaultier Couture' }, 
      { option: 'joseph', label: 'Joseph' }, 
      { option: 'jw anderson', label: 'JW Anderson' }, 
      { option: 'karl lagerfeld', label: 'Karl Lagerfeld' }, 
      { option: 'loewe', label: 'Loewe' }, 
      { option: 'loro piana', label: 'Loro Piana' }, 
      { option: 'louis vitton', label: 'Louis Vuitton' }, 
      { option: 'maison kitsuné', label: 'Maison Kitsuné' }, 
      { option: 'maison rabih kayrouz', label: 'Maison Rabih Kayrouz' }, 
      { option: 'maison sara chraibi', label: 'Maison Sara Chraibi' }, 
      { option: 'maje', label: 'Maje' }, 
      { option: 'manolo blahnik', label: 'Manolo Blahnik' }, 
      { option: 'marchesa', label: 'Marchesa' }, 
      { option: 'mastermind japan', label: 'Mastermind Japan' }, 
      { option: 'maurizio galante', label: 'Maurizio Galante' }, 
      { option: 'max mara', label: 'Max Mara' }, 
      { option: 'michael kors', label: 'Michael Kors' }, 
      { option: 'mikimoto', label: 'Mikimoto' }, 
      { option: 'monique lhuillier', label: 'Monique Lhuillier' }, 
      { option: 'moschino cheap & chic', label: 'Moschino Cheap & Chic' }, 
      { option: 'neighborhood', label: 'Neighborhood' }, 
      { option: 'nicholas kirkwood', label: 'Nicholas Kirkwood' }, 
      { option: 'ozwald boateng', label: 'Ozwald Boateng' }, 
      { option: 'paige denim', label: 'Paige Denim' }, 
      { option: 'palm angels', label: 'Palm Angels' }, 
      { option: 'piaget', label: 'Piaget' }, 
      { option: 'pink tartan', label: 'Pink Tartan' }, 
      { option: 'pomellato', label: 'Pomellato' }, 
      { option: 'prada', label: 'Prada' }, 
      { option: 'proenza schouler', label: 'Proenza Schouler' }, 
      { option: 'rachel zoe', label: 'Rachel Zoe' }, 
      { option: 'rag & bone', label: 'Rag & Bone' }, 
      { option: 'rahul mishra', label: 'Rahul Mishra' }, 
      { option: 'reem acra', label: 'Reem Acra' }, 
      { option: 'reiss', label: 'Reiss' }, 
      { option: 'repossi', label: 'Repossi' }, 
      { option: 'rick owens', label: 'Rick Owens' }, 
      { option: 'roger vivier', label: 'Roger Vivier' }, 
      { option: 'saint laurent', label: 'Saint Laurent' }, 
      { option: 'salvatore ferragamo', label: 'Salvatore Ferragamo' }, 
      { option: 'sandro', label: 'Sandro' }, 
      { option: 'schiaparelli', label: 'Schiaparelli' }, 
      { option: 'schiaparelli couture', label: 'Schiaparelli Couture' }, 
      { option: 'sies marjan', label: 'Sies Marjan' }, 
      { option: 'simone rocha', label: 'Simone Rocha' }, 
      { option: 'sophie hulme', label: 'Sophie Hulme' }, 
      { option: 'sportmax', label: 'Sportmax' }, 
      { option: 'stephane rolland', label: 'Stephane Rolland' }, 
      { option: 'stone island', label: 'Stone Island' }, 
      { option: 'supreme', label: 'Supreme' }, 
      { option: 'tadashi shoji', label: 'Tadashi Shoji' }, 
      { option: 'tasaki', label: 'Tasaki' }, 
      { option: 'ted baker', label: 'Ted Baker' }, 
      { option: 'telfar', label: 'Telfar' }, 
      { option: 'the row', label: 'The Row' }, 
      { option: 'theory', label: 'Theory' }, 
      { option: 'thom sweeney', label: 'Thom Sweeney' }, 
      { option: 'tiffany & co.', label: 'Tiffany & Co.' }, 
      { option: 'tods', label: 'Tods' }, 
      { option: 'tory burch', label: 'Tory Burch' }, 
      { option: 'turnbull & asser', label: 'Turnbull & Asser' }, 
      { option: 'undercover', label: 'Undercover' }, 
      { option: 'valentino haute couture', label: 'Valentino Haute Couture' }, 
      { option: 'van cleef & arpels', label: 'Van Cleef & Arpels' }, 
      { option: 'vera wang', label: 'Vera Wang' }, 
      { option: 'veronica beard', label: 'Veronica Beard' }, 
      { option: 'vetements', label: 'Vetements' }, 
      { option: 'viktor & rolf', label: 'Viktor & Rolf' }, 
      { option: 'vince', label: 'Vince' }, 
      { option: 'vionnet', label: 'Vionnet' }, 
      { option: 'wtaps', label: 'WTAPS' }, 
      { option: 'y-3', label: 'Y-3' }, 
      { option: 'yohji yamamoto', label: 'Yohji Yamamoto' }, 
      { option: 'zimmermann', label: 'Zimmermann' }
    ],
    filterConfig: {
      indexForSearch: true,
      label: 'Дизайнерски марки',
      group: 'secondary',
    },
    showConfig: {
      label: 'Дизайнерски марки',
      isDetail: true,
    },
    saveConfig: {
      label: 'Дизайнерски марки',
      placeholderMessage: 'Селектирай дизайнерска марка…',
      isRequired: false,
      requiredMessage: 'Трябва да изберете дизайнерска марка.',
    },
  },

  // {
  //   key: 'accessories',
  //   scope: 'public',
  //   schemaType: 'multi-enum',
  //   enumOptions: [
  //     { option: 'bell', label: 'Bell' },
  //     { option: 'lights', label: 'Lights' },
  //     { option: 'lock', label: 'Lock' },
  //     { option: 'mudguard', label: 'Mudguard' },
  //   ],
  //   filterConfig: {
  //     indexForSearch: true,
  //     label: 'Accessories',
  //     searchMode: 'has_all',
  //     group: 'secondary',
  //   },
  //   showConfig: {
  //     label: 'Accessories',
  //   },
  //   saveConfig: {
  //     label: 'Accessories',
  //     placeholderMessage: 'Select an option…',
  //     isRequired: false,
  //   },
  // },
  // // An example of how to use transaction type specific custom fields and private data.
  // {
  //   key: 'note',
  //   scope: 'public',
  //   schemaType: 'text',
  //   listingTypeConfig: {
  //     limitToListingTypeIds: true,
  //     listingTypeIds: ['product-selling'],
  //   },
  //   showConfig: {
  //     label: 'Extra notes',
  //   },
  //   saveConfig: {
  //     label: 'Extra notes',
  //     placeholderMessage: 'Some public extra note about this bike...',
  //   },
  // },
  // {
  //   key: 'privatenote',
  //   scope: 'private',
  //   schemaType: 'text',
  //   listingTypeConfig: {
  //     limitToListingTypeIds: true,
  //     listingTypeIds: ['daily-booking'],
  //   },
  //   saveConfig: {
  //     label: 'Private notes',
  //     placeholderMessage: 'Some private note about this bike...',
  //   },
  // },
];

///////////////////////////////////////////////////////////////////////
// Configurations related to listing types and transaction processes //
///////////////////////////////////////////////////////////////////////

// A presets of supported listing configurations
//
// Note 1: The listingTypes come from listingTypes asset nowadays by default.
//         To use this built-in configuration, you need to change the overwrite from configHelper.js
//         (E.g. use mergeDefaultTypesAndFieldsForDebugging func)
// Note 2: transaction type is part of listing type. It defines what transaction process and units
//         are used when transaction is created against a specific listing.

/**
 * Configuration options for listing experience:
 * - listingType:         Unique string. This will be saved to listing's public data on
 *                        EditListingWizard.
 * - label                Label for the listing type. Used as microcopy for options to select
 *                        listing type in EditListingWizard.
 * - transactionType      Set of configurations how this listing type will behave when transaction is
 *                        created.
 *   - process              Transaction process.
 *                          The process must match one of the processes that this client app can handle
 *                          (check src/util/transactions/transaction.js) and the process must also exists in correct
 *                          marketplace environment.
 *   - alias                Valid alias for the aforementioned process. This will be saved to listing's
 *                          public data as transctionProcessAlias and transaction is initiated with this.
 *   - unitType             Unit type is mainly used as pricing unit. This will be saved to
 *                          transaction's protected data.
 *                          Recommendation: don't use same unit types in completely different processes
 *                          ('item' sold should not be priced the same as 'item' booked).
 * - stockType            This is relevant only to listings using default-purchase process.
 *                        If set to 'oneItem', stock management is not showed and the listing is
 *                        considered unique (stock = 1).
 *                        Possible values: 'oneItem' and 'multipleItems'.
 *                        Default: 'multipleItems'.
 * - defaultListingFields These are tied to transaction processes. Different processes have different flags.
 *                        E.g. default-inquiry can toggle price and location to true/false value to indicate,
 *                        whether price (or location) tab should be shown. If defaultListingFields.price is not
 *                        explicitly set to _false_, price will be shown.
 *                        If the location or pickup is not used, listing won't be returned with location search.
 *                        Use keyword search as main search type if location is not enforced.
 *                        The payoutDetails flag allows provider to bypass setting of payout details.
 *                        Note: customers can't order listings, if provider has not set payout details! Monitor
 *                        providers who have not set payout details and contact them to ensure that they add the details.
 */

export const listingTypes = [
  {
    listingType: 'daily-booking',
    label: 'Daily booking',
    transactionType: {
      process: 'default-booking',
      alias: 'default-booking/release-1',
      unitType: 'day',
    },
    defaultListingFields: {
      location: true,
      payoutDetails: true,
    },
  },
  // // Here are some examples for other listingTypes
  // // TODO: SearchPage does not work well if both booking and product selling are used at the same time
  // {
  //   listingType: 'nightly-booking',
  //   label: 'Nightly booking',
  //   transactionType: {
  //     process: 'default-booking',
  //     alias: 'default-booking/release-1',
  //     unitType: 'night',
  //   },
  // },
  // {
  //   listingType: 'hourly-booking',
  //   label: 'Hourly booking',
  //   transactionType: {
  //     process: 'default-booking',
  //     alias: 'default-booking/release-1',
  //     unitType: 'hour',
  //   },
  // },
  // {
  //   listingType: 'product-selling',
  //   label: 'Sell bicycles',
  //   transactionType: {
  //     process: 'default-purchase',
  //     alias: 'default-purchase/release-1',
  //     unitType: 'item',
  //   },
  //   stockType: 'multipleItems',
  //   defaultListingFields: {
  //     shipping: true,
  //     pickup: true,
  //     payoutDetails: true,
  //   },
  // },
  // {
  //   listingType: 'inquiry',
  //   label: 'Inquiry',
  //   transactionType: {
  //     process: 'default-inquiry',
  //     alias: 'default-inquiry/release-1',
  //     unitType: 'inquiry',
  //   },
  //   defaultListingFields: {
  //     price: false,
  //     location: true,
  //   },
  // },
];

// SearchPage can enforce listing query to only those listings with valid listingType
// However, it only works if you have set 'enum' type search schema for the public data fields
//   - listingType
//
//  Similar setup could be expanded to 2 other extended data fields:
//   - transactionProcessAlias
//   - unitType
//
// Read More:
// https://www.sharetribe.com/docs/how-to/manage-search-schemas-with-flex-cli/#adding-listing-search-schemas
export const enforceValidListingType = false;
