/////////////////////////////////////////////////////////
// Configurations related to listing.                  //
// Main configuration here is the extended data config //
/////////////////////////////////////////////////////////

// Note: The listingFields come from listingFields asset nowadays by default.
//       To use this built-in configuration, you need to change the overwrite from configHelper.js
//       (E.g. use mergeDefaultTypesAndFieldsForDebugging func)

/**
 * Configuration options for listing fields (custom extended data fields):
 * - key:                           Unique key for the extended data field.
 * - scope (optional):              Scope of the extended data can be 'public', 'private', or 'metadata'.
 *                                  Default value: 'public'.
 *                                  Note: listing doesn't support 'protected' scope atm.
 * - schemaType (optional):         Schema for this extended data field.
 *                                  This is relevant when rendering components and querying listings.
 *                                  Possible values: 'enum', 'multi-enum', 'text', 'long', 'boolean'.
 * - enumOptions (optional):        Options shown for 'enum' and 'multi-enum' extended data.
 *                                  These are used to render options for inputs and filters on
 *                                  EditListingPage, ListingPage, and SearchPage.
 * - listingTypeConfig (optional):  Relationship configuration against listing types.
 *   - limitToListingTypeIds:         Indicator whether this listing field is relevant to a limited set of listing types.
 *   - listingTypeIds:                An array of listing types, for which this custom listing field is
 *                                    relevant and should be added. This is mandatory if limitToListingTypeIds is true.
 * - categoryConfig (optional):     Relationship configuration against categories.
 *   - limitToCategoryIds:            Indicator whether this listing field is relevant to a limited set of categories.
 *   - categoryIds:                   An array of categories, for which this custom listing field is
 *                                    relevant and should be added. This is mandatory if limitToCategoryIds is true.
 * - filterConfig:                  Filter configuration for listings query.
 *    - indexForSearch (optional):    If set as true, it is assumed that the extended data key has
 *                                    search index in place. I.e. the key can be used to filter
 *                                    listing queries (then scope needs to be 'public').
 *                                    Note: Sharetribe CLI can be used to set search index for the key:
 *                                    https://www.sharetribe.com/docs/references/extended-data/#search-schema
 *                                    Read more about filtering listings with public data keys from API Reference:
 *                                    https://www.sharetribe.com/api-reference/marketplace.html#extended-data-filtering
 *                                    Default value: false,
 *   - filterType:                    Sometimes a single schemaType can be rendered with different filter components.
 *                                    For 'enum' schema, filterType can be 'SelectSingleFilter' or 'SelectMultipleFilter'
 *   - label:                         Label for the filter, if the field can be used as query filter
 *   - searchMode (optional):         Search mode for indexed data with multi-enum schema.
 *                                    Possible values: 'has_all' or 'has_any'.
 *   - group:                         SearchPageWithMap has grouped filters. Possible values: 'primary' or 'secondary'.
 * - showConfig:                    Configuration for rendering listing. (How the field should be shown.)
 *   - label:                         Label for the saved data.
 *   - isDetail                       Can be used to hide detail row (of type enum, boolean, or long) from listing page.
 *                                    Default value: true,
 * - saveConfig:                    Configuration for adding and modifying extended data fields.
 *   - label:                         Label for the input field.
 *   - placeholderMessage (optional): Default message for user input.
 *   - isRequired (optional):         Is the field required for providers to fill
 *   - requiredMessage (optional):    Message for those fields, which are mandatory.
 */
export const listingFields = [
  {
    key: 'color',
    scope: 'public',
    schemaType: 'multi-enum',
    enumOptions: [
      { option: 'rojo',         label: 'Rojo' },
      { option: 'rosa',         label: 'Rosa' },
      { option: 'amarillo',     label: 'Amarillo' },
      { option: 'naranja',      label: 'Naranja' },
      { option: 'dorado',       label: 'Dorado' },
      { option: 'plateado',     label: 'Plateado' },
      { option: 'verde',        label: 'Verde' },
      { option: 'azul',         label: 'Azul' },
      { option: 'morado',       label: 'Morado' },
      { option: 'negro',        label: 'Negro' },
      { option: 'gris',         label: 'Gris' },
      { option: 'blanco',       label: 'Blanco' },
      { option: 'crema',        label: 'Crema' },
      { option: 'cafe',         label: 'Café' },
      { option: 'animal-print', label: 'Animal Print' },
      { option: 'floral-print', label: 'Floral' },
      { option: 'multicolor',   label: 'Multicolor' },
    ],
    filterConfig: {
      indexForSearch: true,
      showFilter: true,
      filterType: 'SelectMultipleFilter',
      searchMode: 'has_any',
      label: 'Color',
      group: 'primary',
    },
    showConfig: {
      label: 'Color',
      isDetail: true,
      unselectedOptions: false,
    },
    saveConfig: {
      label: 'Color',
      isRequired: true,
      requiredMessage: 'Debes seleccionar al menos un color.',
    },
  },
  {
    key: 'all_sizes',
    scope: 'public',
    schemaType: 'multi-enum',
    enumOptions: [
      // Standard
      { option: 'unitalla', label: 'Unitalla' },
      { option: 'xxs',      label: 'XXS' },
      { option: 'xs',       label: 'XS' },
      { option: 's',        label: 'S' },
      { option: 'm',        label: 'M' },
      { option: 'l',        label: 'L' },
      { option: 'xl',       label: 'XL' },
      { option: 'xxl',      label: 'XXL' },
      { option: 'xxxl',     label: 'XXXL' },
      // MX numeric
      { option: 'mx_22',    label: 'MX 22' },
      { option: 'mx_24',    label: 'MX 24' },
      { option: 'mx_26',    label: 'MX 26' },
      { option: 'mx_28',    label: 'MX 28' },
      { option: 'mx_30',    label: 'MX 30' },
      { option: 'mx_32',    label: 'MX 32' },
      { option: 'mx_34',    label: 'MX 34' },
      { option: 'mx_36',    label: 'MX 36' },
      { option: 'mx_38',    label: 'MX 38' },
      { option: 'mx_40',    label: 'MX 40' },
      { option: 'mx_42',    label: 'MX 42' },
      { option: 'mx_44',    label: 'MX 44' },
      // US numeric
      { option: 'us_00',    label: 'US 00' },
      { option: 'us_0',     label: 'US 0' },
      { option: 'us_2',     label: 'US 2' },
      { option: 'us_4',     label: 'US 4' },
      { option: 'us_6',     label: 'US 6' },
      { option: 'us_8',     label: 'US 8' },
      { option: 'us_10',    label: 'US 10' },
      { option: 'us_12',    label: 'US 12' },
      { option: 'us_14',    label: 'US 14' },
      { option: 'us_16',    label: 'US 16' },
      // Curvy
      { option: 'curvy_1x', label: '1X' },
      { option: 'curvy_2x', label: '2X' },
      { option: 'curvy_3x', label: '3X' },
      { option: 'curvy_4x', label: '4X' },
      { option: 'curvy_5x', label: '5X' },
      { option: 'curvy_6x', label: '6X' },
    ],
    filterConfig: {
      indexForSearch: true,
      showFilter: true,
      filterType: 'SelectMultipleFilter',
      searchMode: 'has_any',
      label: 'Talla',
      group: 'primary',
    },
    showConfig: {
      label: 'Tallas',
      isDetail: true,
      unselectedOptions: false,
    },
    saveConfig: {
      label: 'Tallas',
      isRequired: true,
      requiredMessage: 'Debes seleccionar al menos una talla.',
    },
  },
  {
    key: 'brand',
    scope: 'public',
    schemaType: 'enum',
    enumOptions: [
      { option: 'other-stories', label: '& Other Stories' },
      { option: '1-state', label: '1.STATE' },
      { option: '1-8-takamura', label: '1/8 Takamura' },
      { option: '525', label: '525' },
      { option: '7-for-all-mankind', label: '7 For All Mankind' },
      { option: 'a-bathing-ape-bape', label: 'A Bathing Ape (BAPE)' },
      { option: 'a-roege-hove', label: 'A. Roege Hove' },
      { option: 'a-l-c', label: 'A.L.C.' },
      { option: 'a-p-c', label: 'A.P.C.' },
      { option: 'abercrombie-fitch', label: 'Abercrombie & Fitch' },
      { option: 'acacia', label: 'Acacia' },
      { option: 'acne-studios', label: 'Acne Studios' },
      { option: 'adidas', label: 'Adidas' },
      { option: 'adidas-by-stella-mccartney', label: 'adidas by Stella McCartney' },
      { option: 'aeropostale', label: 'Aeropostale' },
      { option: 'ag-adriano-goldschmied', label: 'AG Adriano Goldschmied' },
      { option: 'agolde', label: 'AGOLDE' },
      { option: 'agua-bendita', label: 'Agua Bendita' },
      { option: 'aje', label: 'Aje' },
      { option: 'ala-a', label: 'Alaïa' },
      { option: 'alexander-mcqueen', label: 'Alexander McQueen' },
      { option: 'alexander-wang', label: 'Alexander Wang' },
      { option: 'alexandre-herchcovitch', label: 'Alexandre Herchcovitch' },
      { option: 'alexandre-vauthier', label: 'Alexandre Vauthier' },
      { option: 'alexia-ulibarri', label: 'Alexia Ulibarri' },
      { option: 'alexis', label: 'Alexis' },
      { option: 'alice-olivia', label: 'Alice + Olivia' },
      { option: 'all-for-ramon', label: 'All for Ramon' },
      { option: 'allsaints', label: 'AllSaints' },
      { option: 'alo-yoga', label: 'Alo Yoga' },
      { option: 'amanda-uprichard', label: 'Amanda Uprichard' },
      { option: 'amaro', label: 'Amaro' },
      { option: 'ambush', label: 'AMBUSH' },
      { option: 'american-eagle', label: 'American Eagle' },
      { option: 'amo', label: 'AMO' },
      { option: 'amour-vert', label: 'Amour Vert' },
      { option: 'andrea-landa', label: 'Andrea Landa' },
      { option: 'angel-grave', label: 'Angel Grave' },
      { option: 'angel-sanchez', label: 'Angel Sanchez' },
      { option: 'animale', label: 'Animale' },
      { option: 'animazul', label: 'Animazul' },
      { option: 'anine-bing', label: 'ANINE BING' },
      { option: 'ann-taylor', label: 'Ann Taylor' },
      { option: 'anna-october', label: 'Anna October' },
      { option: 'anntarah', label: 'Anntarah' },
      { option: 'apiece-apart', label: 'Apiece Apart' },
      { option: 'aqua-blu-australia', label: 'AQUA BLU Australia' },
      { option: 'area', label: 'AREA' },
      { option: 'arianne-elmy', label: 'Arianne Elmy' },
      { option: 'aritzia', label: 'Aritzia' },
      { option: 'arroz-con-leche', label: 'Arroz con leche' },
      { option: 'as-by-df', label: 'AS by DF' },
      { option: 'ash', label: 'ASH' },
      { option: 'asics', label: 'Asics' },
      { option: 'astr-the-label', label: 'ASTR the Label' },
      { option: 'atoir', label: 'Atoir' },
      { option: 'autumn-adeigbo', label: 'Autumn Adeigbo' },
      { option: 'ay-not-dead', label: 'Ay Not Dead' },
      { option: 'aya-muse', label: 'Aya Muse' },
      { option: 'ayni', label: 'Ayni' },
      { option: 'b-low-the-belt', label: 'B-Low the Belt' },
      { option: 'balenciaga', label: 'Balenciaga' },
      { option: 'banana-republic', label: 'Banana Republic' },
      { option: 'baobab', label: 'Baobab' },
      { option: 'basicos-de-m-xico', label: 'Basicos de México' },
      { option: 'baum', label: 'Baum' },
      { option: 'beach-bunny', label: 'Beach Bunny' },
      { option: 'beis', label: 'BEIS' },
      { option: 'bella-dahl', label: 'Bella Dahl' },
      { option: 'benedetta-bruzziches', label: 'Benedetta Bruzziches' },
      { option: 'benito-santos', label: 'Benito Santos' },
      { option: 'benjamin-benmoyal', label: 'Benjamin Benmoyal' },
      { option: 'bershka', label: 'Bershka' },
      { option: 'beyond-yoga', label: 'Beyond Yoga' },
      { option: 'bishop-young', label: 'Bishop + Young' },
      { option: 'black-by-maria-silver', label: 'Black by Maria Silver' },
      { option: 'blanknyc', label: 'BLANKNYC' },
      { option: 'blue-man', label: 'Blue Man' },
      { option: 'bolazo', label: 'Bolazo' },
      { option: 'boohoo', label: 'Boohoo' },
      { option: 'borgo-de-nor', label: 'Borgo De Nor' },
      { option: 'bottega-veneta', label: 'Bottega Veneta' },
      { option: 'boys-lie', label: 'Boys Lie' },
      { option: 'brandon-maxwell', label: 'Brandon Maxwell' },
      { option: 'brandy-melville', label: 'Brandy Melville' },
      { option: 'brixton', label: 'Brixton' },
      { option: 'brochu-walker', label: 'Brochu Walker' },
      { option: 'bronx-and-banco', label: 'Bronx and Banco' },
      { option: 'burberry', label: 'Burberry' },
      { option: 'by-far', label: 'By Far' },
      { option: 'by-malene-birger', label: 'By Malene Birger' },
      { option: 'c-meo', label: 'C/MEO' },
      { option: 'cala-de-la-cruz', label: 'Cala de la Cruz' },
      { option: 'callahan', label: 'Callahan' },
      { option: 'calvin-klein', label: 'Calvin Klein' },
      { option: 'camila-coelho', label: 'Camila Coelho' },
      { option: 'camilla', label: 'Camilla' },
      { option: 'camilla-and-marc', label: 'CAMILLA AND MARC' },
      { option: 'cara-cara', label: 'Cara Cara' },
      { option: 'carla-fern-ndez', label: 'Carla Fernández' },
      { option: 'carmen-llaguno', label: 'Carmen Llaguno' },
      { option: 'carolina-herrera', label: 'Carolina Herrera' },
      { option: 'casa-chiqui', label: 'Casa Chiqui' },
      { option: 'cecilie-bahnsen', label: 'Cecilie Bahnsen' },
      { option: 'celine', label: 'Celine' },
      { option: 'champion', label: 'Champion' },
      { option: 'chanel', label: 'Chanel' },
      { option: 'chico-s', label: "Chico's" },
      { option: 'christy-dawn', label: 'Christy Dawn' },
      { option: 'cider', label: 'Cider' },
      { option: 'cihuah', label: 'Cihuah' },
      { option: 'cinq-sept', label: 'Cinq à Sept' },
      { option: 'citizens-of-humanity', label: 'Citizens of Humanity' },
      { option: 'cleobella', label: 'Cleobella' },
      { option: 'clio-peppiatt', label: 'Clio Peppiatt' },
      { option: 'club-l-london', label: 'Club L London' },
      { option: 'coach', label: 'Coach' },
      { option: 'collectiva-concepci-n', label: 'Collectiva Concepción' },
      { option: 'columbia', label: 'Columbia' },
      { option: 'commando', label: 'Commando' },
      { option: 'comme-des-gar-ons', label: 'Comme des Garçons' },
      { option: 'converse', label: 'Converse' },
      { option: 'cora-groppo', label: 'Cora Groppo' },
      { option: 'cos', label: 'COS' },
      { option: 'costaiia', label: 'Costaiia' },
      { option: 'cotton-citizen', label: 'COTTON CITIZEN' },
      { option: 'cotton-on', label: 'Cotton On' },
      { option: 'cotton-project', label: 'Cotton Project' },
      { option: 'cult-gaia', label: 'Cult Gaia' },
      { option: 'current-elliott', label: 'Current/Elliott' },
      { option: 'cushnie', label: 'Cushnie' },
      { option: 'daisy-street', label: 'Daisy Street' },
      { option: 'david-koma', label: 'David Koma' },
      { option: 'daydreamer', label: 'DAYDREAMER' },
      { option: 'de-loreta', label: 'De Loreta' },
      { option: 'deiji-studios', label: 'Deiji Studios' },
      { option: 'delfi-collective', label: 'DELFI Collective' },
      { option: 'dennis-basso', label: 'Dennis Basso' },
      { option: 'derek-lam-10-crosby', label: 'Derek Lam 10 Crosby' },
      { option: 'diane-von-f-rstenberg', label: 'Diane von Fürstenberg' },
      { option: 'diaz-garza', label: 'Diaz Garza' },
      { option: 'dion-lee', label: 'Dion Lee' },
      { option: 'dior', label: 'Dior' },
      { option: 'dkny', label: 'DKNY' },
      { option: 'dl1961', label: 'DL1961' },
      { option: 'donni', label: 'Donni' },
      { option: 'dr-barbara-sturm', label: 'Dr. Barbara Sturm' },
      { option: 'dra', label: 'DRA' },
      { option: 'drome', label: 'DROMe' },
      { option: 'dsquared2', label: 'Dsquared2' },
      { option: 'dundas', label: 'Dundas' },
      { option: 'dune-london', label: 'Dune London' },
      { option: 'duvetica', label: 'DUVETICA' },
      { option: 'eberjey', label: 'Eberjey' },
      { option: 'effie-kats', label: 'Effie Kats' },
      { option: 'eiko-ai', label: 'EIKO AI' },
      { option: 'eileen-fisher', label: 'Eileen Fisher' },
      { option: 'eleven-six', label: 'Eleven Six' },
      { option: 'elie-saab', label: 'Elie Saab' },
      { option: 'elliatt', label: 'ELLIATT' },
      { option: 'ellie-mae', label: 'Ellie Mae' },
      { option: 'else', label: 'ELSE' },
      { option: 'emilio-pucci', label: 'Emilio Pucci' },
      { option: 'emma-mulholland-on-holiday', label: 'Emma Mulholland on Holiday' },
      { option: 'enza-costa', label: 'ENZA COSTA' },
      { option: 'eres', label: 'Eres' },
      { option: 'erin-snow', label: 'Erin Snow' },
      { option: 'esant', label: 'ESANT' },
      { option: 'escada', label: 'Escada' },
      { option: 'escudo', label: 'Escudo' },
      { option: 'escvdo', label: 'ESCVDO' },
      { option: 'esprit', label: 'Esprit' },
      { option: 'eterne', label: 'Eterne' },
      { option: 'ethno', label: 'ETHNO' },
      { option: 'etro', label: 'Etro' },
      { option: 'eva-franco', label: 'Eva Franco' },
      { option: 'everlane', label: 'Everlane' },
      { option: 'express', label: 'Express' },
      { option: 'extra-af', label: 'EXTRA AF' },
      { option: 'f-words', label: 'F.WORDS' },
      { option: 'faherty', label: 'Faherty' },
      { option: 'faithfull-the-brand', label: 'Faithfull the Brand' },
      { option: 'farai-london', label: 'Farai London' },
      { option: 'farm-rio', label: 'FARM Rio' },
      { option: 'fashion-nova', label: 'Fashion Nova' },
      { option: 'favorite-daughter', label: 'FAVORITE DAUGHTER' },
      { option: 'fe-noel', label: 'Fe Noel' },
      { option: 'fendi', label: 'Fendi' },
      { option: 'feng-chen-wang', label: 'Feng Chen Wang' },
      { option: 'ferragamo', label: 'FERRAGAMO' },
      { option: 'fila', label: 'Fila' },
      { option: 'find-me-now', label: 'Find Me Now' },
      { option: 'forever-21', label: 'Forever 21' },
      { option: 'frame', label: 'FRAME' },
      { option: 'francesca-miranda', label: 'Francesca Miranda' },
      { option: 'frankies-bikinis', label: 'Frankies Bikinis' },
      { option: 'free-easy', label: 'Free & Easy' },
      { option: 'free-people', label: 'Free People' },
      { option: 'freya', label: 'FREYA' },
      { option: 'furla', label: 'Furla' },
      { option: 'gabriela-hearst', label: 'Gabriela Hearst' },
      { option: 'ganni', label: 'Ganni' },
      { option: 'gap', label: 'Gap' },
      { option: 'garage', label: 'Garage' },
      { option: 'gaudy-mercy', label: 'Gaudy Mercy' },
      { option: 'gauge81', label: 'GAUGE81' },
      { option: 'generation-love', label: 'Generation Love' },
      { option: 'gentle-monster', label: 'Gentle Monster' },
      { option: 'gia-borghini', label: 'GIA BORGHINI' },
      { option: 'girlfriend-collective', label: 'Girlfriend Collective' },
      { option: 'givenchy', label: 'Givenchy' },
      { option: 'good-american', label: 'Good American' },
      { option: 'grisino', label: 'Grisino' },
      { option: 'grlfrnd', label: 'GRLFRND' },
      { option: 'gucci', label: 'Gucci' },
      { option: 'guess', label: 'Guess' },
      { option: 'gwyneth-shoes', label: 'Gwyneth Shoes' },
      { option: 'gypz', label: 'GYPZ' },
      { option: 'h-m', label: 'H&M' },
      { option: 'haight', label: 'Haight' },
      { option: 'halston', label: 'Halston' },
      { option: 'hanky-panky', label: 'Hanky Panky' },
      { option: 'hanro', label: 'Hanro' },
      { option: 'hello-molly', label: 'Hello Molly' },
      { option: 'helmut-lang', label: 'Helmut Lang' },
      { option: 'helsa', label: 'Helsa' },
      { option: 'herm-s', label: 'Hermès' },
      { option: 'hern-n-herdez', label: 'Hernán Herdez' },
      { option: 'herve-leger', label: 'Herve Leger' },
      { option: 'hollister', label: 'Hollister' },
      { option: 'house-of-cb', label: 'House of CB' },
      { option: 'house-of-harlow-1960', label: 'House of Harlow 1960' },
      { option: 'house-of-sunny', label: 'House of Sunny' },
      { option: 'hunter', label: 'Hunter' },
      { option: 'hunza-g', label: 'HUNZA G' },
      { option: 'i-am-gia', label: 'I.AM.GIA' },
      { option: 'iceberg', label: 'Iceberg' },
      { option: 'intimately-free-people', label: 'Intimately Free People' },
      { option: 'iro', label: 'IRO' },
      { option: 'isa-boulder', label: 'Isa Boulder' },
      { option: 'isa-tapia', label: 'Isa Tapia' },
      { option: 'isabel-marant', label: 'Isabel Marant' },
      { option: 'issey-miyake', label: 'Issey Miyake' },
      { option: 'j-crew', label: 'J.Crew' },
      { option: 'jacquemus', label: 'Jacquemus' },
      { option: 'jade-swim', label: 'Jade Swim' },
      { option: 'jaggar', label: 'JAGGAR' },
      { option: 'james-perse', label: 'James Perse' },
      { option: 'janessa-leone', label: 'Janessa Leone' },
      { option: 'jazm-n-chebar', label: 'Jazmín Chebar' },
      { option: 'jean-paul-gaultier', label: 'Jean Paul Gaultier' },
      { option: 'jeffrey-campbell', label: 'Jeffrey Campbell' },
      { option: 'jill-jill-stuart', label: 'JILL Jill Stuart' },
      { option: 'joah-brown', label: 'Joah Brown' },
      { option: 'joao-maraschin', label: 'Joao Maraschin' },
      { option: 'johanna-ortiz', label: 'Johanna Ortiz' },
      { option: 'jonathan-simkhai', label: 'Jonathan Simkhai' },
      { option: 'jones-new-york', label: 'Jones New York' },
      { option: 'joostricot', label: 'JoosTricot' },
      { option: 'jordan', label: 'Jordan' },
      { option: 'juicy-couture', label: 'Juicy Couture' },
      { option: 'julia-y-renata', label: 'Julia y Renata' },
      { option: 'julietta', label: 'JULIETTA' },
      { option: 'just-bee-queen', label: 'Just Bee Queen' },
      { option: 'jw-anderson', label: 'JW Anderson' },
      { option: 'jw-pei', label: 'JW PEI' },
      { option: 'kaanas', label: 'KAANAS' },
      { option: 'kappa', label: 'Kappa' },
      { option: 'karen-millen', label: 'KAREN MILLEN' },
      { option: 'karla-co', label: 'KARLA + CO' },
      { option: 'kat-the-label', label: 'KAT THE LABEL' },
      { option: 'kate-spade', label: 'Kate Spade' },
      { option: 'kenzo', label: 'Kenzo' },
      { option: 'kero-design', label: 'Kero Design' },
      { option: 'khaite', label: 'KHAITE' },
      { option: 'killa', label: 'Killa' },
      { option: 'kim-shui', label: 'Kim Shui' },
      { option: 'kimhekim', label: 'KIMHEKIM' },
      { option: 'kindom', label: 'KINDOM' },
      { option: 'kivari', label: 'KIVARI' },
      { option: 'koral', label: 'KORAL' },
      { option: 'kosiuko', label: 'Kosiuko' },
      { option: 'kris-goyri', label: 'Kris Goyri' },
      { option: 'l-academie', label: "L'Academie" },
      { option: 'l-space', label: 'L*Space' },
      { option: 'la-detresse', label: 'La Detresse' },
      { option: 'la-joya-design', label: 'La Joya Design' },
      { option: 'lack-of-color', label: 'Lack of Color' },
      { option: 'lanius', label: 'LANIUS' },
      { option: 'lapointe', label: 'Lapointe' },
      { option: 'laquan-smith', label: 'LaQuan Smith' },
      { option: 'las-pepas', label: 'Las Pepas' },
      { option: 'laura-lombardi', label: 'Laura Lombardi' },
      { option: 'le-set', label: 'LE SET' },
      { option: 'le-specs', label: 'Le Specs' },
      { option: 'lee', label: 'Lee' },
      { option: 'lee-mathews', label: 'Lee Mathews' },
      { option: 'lenny-niemeyer', label: 'Lenny Niemeyer' },
      { option: 'levi-s', label: "LEVI'S" },
      { option: 'libertine', label: 'Libertine' },
      { option: 'likely', label: 'LIKELY' },
      { option: 'lina-osorio', label: 'Lina Osorio' },
      { option: 'lisa-marie-fernandez', label: 'Lisa Marie Fernandez' },
      { option: 'liz-claiborne', label: 'Liz Claiborne' },
      { option: 'loewe', label: 'Loewe' },
      { option: 'lollipop', label: 'Lollipop' },
      { option: 'loraine-holmes', label: 'Loraine Holmes' },
      { option: 'louis-vuitton', label: 'Louis Vuitton' },
      { option: 'lovers-and-friends', label: 'Lovers and Friends' },
      { option: 'loveshackfancy', label: 'LoveShackFancy' },
      { option: 'lpa', label: 'LPA' },
      { option: 'lspace', label: 'LSPACE' },
      { option: 'luciana-balderrama', label: 'Luciana Balderrama' },
      { option: 'lululemon', label: 'Lululemon' },
      { option: 'luv-aj', label: 'Luv AJ' },
      { option: 'luz-brice-o', label: 'Luz Briceño' },
      { option: 'maison-irem', label: 'Maison Irem' },
      { option: 'maison-kitsun', label: 'Maison Kitsuné' },
      { option: 'maje', label: 'Maje' },
      { option: 'majorelle', label: 'MAJORELLE' },
      { option: 'makeno', label: 'Makeno' },
      { option: 'malmo', label: 'Malmo' },
      { option: 'malvestida-studio', label: 'Malvestida Studio' },
      { option: 'mancandy', label: 'Mancandy' },
      { option: 'mango', label: 'Mango' },
      { option: 'mara-hoffman', label: 'Mara Hoffman' },
      { option: 'marc-jacobs', label: 'Marc Jacobs' },
      { option: 'marchesa-notte', label: 'Marchesa Notte' },
      { option: 'marcia', label: 'Marcia' },
      { option: 'mariana-dappiano', label: 'Mariana Dappiano' },
      { option: 'marika-vera', label: 'Marika Vera' },
      { option: 'marine-serre', label: 'Marine Serre' },
      { option: 'marni', label: 'Marni' },
      { option: 'marysia', label: 'Marysia' },
      { option: 'massimo-dutti', label: 'Massimo Dutti' },
      { option: 'material-tbilisi', label: 'Material Tbilisi' },
      { option: 'matin', label: 'MATIN' },
      { option: 'mavi', label: 'Mavi' },
      { option: 'maygel-coronel', label: 'Maygel Coronel' },
      { option: 'melissa-odabash', label: 'Melissa Odabash' },
      { option: 'mercedes-salazar', label: 'Mercedes Salazar' },
      { option: 'michael-costello', label: 'Michael Costello' },
      { option: 'michael-kors', label: 'Michael Kors' },
      { option: 'michael-stars', label: 'Michael Stars' },
      { option: 'michelle-mason', label: 'Michelle Mason' },
      { option: 'mikoh', label: 'Mikoh' },
      { option: 'milly', label: 'Milly' },
      { option: 'min-agostini', label: 'Min Agostini' },
      { option: 'minena', label: 'Minena' },
      { option: 'misa-los-angeles', label: 'MISA Los Angeles' },
      { option: 'missguided', label: 'Missguided' },
      { option: 'missoni', label: 'Missoni' },
      { option: 'mitsa', label: 'Mitsa' },
      { option: 'miu-miu', label: 'Miu Miu' },
      { option: 'mlm-label', label: 'MLM LABEL' },
      { option: 'mola-sasa', label: 'Mola Sasa' },
      { option: 'moncler', label: 'Moncler' },
      { option: 'monrow', label: 'Monrow' },
      { option: 'monse', label: 'Monse' },
      { option: 'montce', label: 'Montce' },
      { option: 'montserat-messeguer', label: 'Montserat Messeguer' },
      { option: 'moque', label: 'Moque' },
      { option: 'mutma', label: 'Mutma' },
      { option: 'nabel-martins', label: 'Nabel Martins' },
      { option: 'nadia-dafri', label: 'Nadia Dafri' },
      { option: 'nanushka', label: 'Nanushka' },
      { option: 'nasty-gal', label: 'Nasty Gal' },
      { option: 'naya', label: 'Naya' },
      { option: 'nbd', label: 'NBD' },
      { option: 'needle-thread', label: 'Needle & Thread' },
      { option: 'nefelibata', label: 'Nefelibata' },
      { option: 'neochilango', label: 'Neochilango' },
      { option: 'neuw-denim', label: 'Neuw Denim' },
      { option: 'new-balance', label: 'New Balance' },
      { option: 'nicholas', label: 'Nicholas' },
      { option: 'nido', label: 'Nido' },
      { option: 'nike', label: 'Nike' },
      { option: 'nili-lotan', label: 'NILI LOTAN' },
      { option: 'nina-ricci', label: 'Nina Ricci' },
      { option: 'ninety-percent', label: 'Ninety Percent' },
      { option: 'nookie', label: 'Nookie' },
      { option: 'nora-parada', label: 'Nora Parada' },
      { option: 'norma-kamali', label: 'Norma Kamali' },
      { option: 'nous-etudions', label: 'Nous Etudions' },
      { option: 'oak-fort', label: 'Oak + Fort' },
      { option: 'off-white', label: 'Off-White' },
      { option: 'oh-polly', label: 'Oh Polly' },
      { option: 'on', label: 'ON' },
      { option: 'onia', label: 'Onia' },
      { option: 'onitsuka-tiger', label: 'Onitsuka Tiger' },
      { option: 'opening-ceremony', label: 'Opening Ceremony' },
      { option: 'organic-basics', label: 'Organic Basics' },
      { option: 'orseund-iris', label: 'Orseund Iris' },
      { option: 'oscar-de-la-renta', label: 'Oscar de la Renta' },
      { option: 'os-ree', label: 'Oséree' },
      { option: 'osklen', label: 'Osklen' },
      { option: 'otros', label: 'Otros' },
      { option: 'outerknown', label: 'Outerknown' },
      { option: 'oysho', label: 'Oysho' },
      { option: 'p-e-nation', label: 'P.E Nation' },
      { option: 'pacsun', label: 'PacSun' },
      { option: 'pact', label: 'Pact' },
      { option: 'paige', label: 'Paige' },
      { option: 'paka', label: 'PAKA' },
      { option: 'palm-angels', label: 'Palm Angels' },
      { option: 'palm-by-palmacea', label: 'Palm by Palmacea' },
      { option: 'palmacea', label: 'Palmacea' },
      { option: 'paloma-wool', label: 'Paloma Wool' },
      { option: 'parade', label: 'Parade' },
      { option: 'patagonia', label: 'Patagonia' },
      { option: 'patbo', label: 'PatBO' },
      { option: 'patricio-campillo', label: 'Patricio Campillo' },
      { option: 'patta', label: 'Patta' },
      { option: 'pay-s', label: "Pay's" },
      { option: 'pendleton', label: 'Pendleton' },
      { option: 'peony', label: 'Peony' },
      { option: 'people-tree', label: 'People Tree' },
      { option: 'peter-do', label: 'Peter Do' },
      { option: 'pfeiffer', label: 'Pfeiffer' },
      { option: 'ph5', label: 'PH5' },
      { option: 'philosophy-di-lorenzo-serafini', label: 'Philosophy di Lorenzo Serafini' },
      { option: 'pia', label: 'PIA' },
      { option: 'piel-canela', label: 'Piel Canela' },
      { option: 'pineda-covalin', label: 'Pineda Covalin' },
      { option: 'pink-magnolia', label: 'PINK MAGNOLIA' },
      { option: 'pinko', label: 'PINKO' },
      { option: 'pistola-denim', label: 'Pistola Denim' },
      { option: 'polit-cnico', label: 'Politécnico' },
      { option: 'polo-ralph-lauren', label: 'Polo Ralph Lauren' },
      { option: 'port-de-bras', label: 'Port de Bras' },
      { option: 'prada', label: 'Prada' },
      { option: 'prettylittlething', label: 'PrettyLittleThing' },
      { option: 'princess-polly', label: 'Princess Polly' },
      { option: 'privacy-please', label: 'Privacy Please' },
      { option: 'proenza-schouler', label: 'Proenza Schouler' },
      { option: 'pucci', label: 'PUCCI' },
      { option: 'pull-bear', label: 'Pull & Bear' },
      { option: 'puma', label: 'Puma' },
      { option: 'puna', label: 'Puna' },
      { option: 'pura', label: 'Pura' },
      { option: 'qaytu', label: 'Qaytu' },
      { option: 'quay', label: 'Quay' },
      { option: 'rachel-comey', label: 'Rachel Comey' },
      { option: 'rag-bone', label: 'Rag & Bone' },
      { option: 'rails', label: 'Rails' },
      { option: 'raisa-vanessa', label: 'RAISA VANESSA' },
      { option: 'ralph-lauren', label: 'Ralph Lauren' },
      { option: 'ramy-brook', label: 'RAMY BROOK' },
      { option: 'rapsodia', label: 'Rapsodia' },
      { option: 'rat-boa', label: 'Rat & Boa' },
      { option: 're-done', label: 'Re/Done' },
      { option: 'rebecca-minkoff', label: 'Rebecca Minkoff' },
      { option: 'reebok', label: 'Reebok' },
      { option: 'reformation', label: 'Reformation' },
      { option: 'rei', label: 'REI' },
      { option: 'reserva', label: 'Reserva' },
      { option: 'retrof-te', label: 'Retrofête' },
      { option: 'revolve', label: 'Revolve' },
      { option: 'rhea-the-label', label: 'Rhea the label' },
      { option: 'rhode', label: 'RHODE' },
      { option: 'rianne-nl', label: 'RIANNE-NL' },
      { option: 'rick-owens', label: 'Rick Owens' },
      { option: 'rixo', label: 'Rixo' },
      { option: 'rococo-sand', label: 'ROCOCO SAND' },
      { option: 'ropa-doce', label: 'Ropa Doce' },
      { option: 'rta', label: 'RTA' },
      { option: 'rue-sophie', label: 'Rue SOPHIE' },
      { option: 'rue-stiic', label: 'Rue Stiic' },
      { option: 'rumer', label: 'Rumer' },
      { option: 'sabina-musayev', label: 'Sabina Musayev' },
      { option: 'sablyn', label: 'Sablyn' },
      { option: 'sabrina-ol', label: 'Sabrina ol' },
      { option: 'sacai', label: 'SACAI' },
      { option: 'saint-laurent', label: 'Saint Laurent' },
      { option: 'saloni', label: 'Saloni' },
      { option: 'salvatore-ferragamo', label: 'Salvatore Ferragamo' },
      { option: 'sam-edelman', label: 'Sam Edelman' },
      { option: 'sams-e-sams-e', label: 'Samsøe Samsøe' },
      { option: 'sandra-weil', label: 'Sandra Weil' },
      { option: 'sandro', label: 'Sandro' },
      { option: 'santa-brands', label: 'Santa Brands' },
      { option: 'santos', label: 'Santos' },
      { option: 'sau-lee', label: 'Sau Lee' },
      { option: 'sayonara', label: 'Sayonara' },
      { option: 'sea', label: 'Sea' },
      { option: 'seafolly', label: 'Seafolly' },
      { option: 'see-by-chlo', label: 'See by Chloé' },
      { option: 'self-portrait', label: 'Self-Portrait' },
      { option: 'selkie', label: 'SELKIE' },
      { option: 'ser-o-ya', label: 'SER.O.YA' },
      { option: 'serg', label: 'Sergé' },
      { option: 'shona-joy', label: 'Shona Joy' },
      { option: 'show-me-your-mumu', label: 'Show Me Your Mumu' },
      { option: 'siento', label: 'Siento' },
      { option: 'significant-other', label: 'Significant Other' },
      { option: 'silvia-tcherassi', label: 'Silvia Tcherassi' },
      { option: 'simon-miller', label: 'Simon Miller' },
      { option: 'sir', label: 'Sir' },
      { option: 'sir-the-label', label: 'SIR the label' },
      { option: 'sisa', label: 'SISA' },
      { option: 'sisa-slow', label: 'Sisa Slow' },
      { option: 'sisay', label: 'SISAY' },
      { option: 'skims', label: 'Skims' },
      { option: 'solid-striped', label: 'Solid & Striped' },
      { option: 'something-co', label: 'Something Co' },
      { option: 'song-of-style', label: 'Song of Style' },
      { option: 'sonia-rykiel', label: 'Sonia Rykiel' },
      { option: 'spanx', label: 'Spanx' },
      { option: 'spell', label: 'Spell' },
      { option: 'splendid', label: 'Splendid' },
      { option: 'sporty-rich', label: 'Sporty & Rich' },
      { option: 'srita-galindo', label: 'Srita Galindo' },
      { option: 'st-dom', label: 'St. Dom' },
      { option: 'staud', label: 'Staud' },
      { option: 'steel', label: 'Steel' },
      { option: 'stella-mccartney', label: 'Stella McCartney' },
      { option: 'stella-solar', label: 'Stella Solar' },
      { option: 'stone-cold-fox', label: 'Stone Cold Fox' },
      { option: 'stone-island', label: 'Stone Island' },
      { option: 'stradivarius', label: 'Stradivarius' },
      { option: 'stratto', label: 'Stratto' },
      { option: 'stuart-weitzman', label: 'Stuart Weitzman' },
      { option: 'studio-conchita', label: 'Studio Conchita' },
      { option: 'st-ssy', label: 'Stüssy' },
      { option: 'stylest', label: 'STYLEST' },
      { option: 'suboo', label: 'Suboo' },
      { option: 'suki-waterhouse-x-revolve', label: 'Suki Waterhouse x REVOLVE' },
      { option: 'sumy-kujon', label: 'Sumy Kujon' },
      { option: 'sundress', label: 'Sundress' },
      { option: 'sundry', label: 'Sundry' },
      { option: 'superdown', label: 'Superdown' },
      { option: 'superga', label: 'Superga' },
      { option: 'supreme', label: 'Supreme' },
      { option: 'susana-monaco', label: 'Susana Monaco' },
      { option: 'tach-clothing', label: 'Tach Clothing' },
      { option: 'talbots', label: 'Talbots' },
      { option: 'tanya-taylor', label: 'Tanya Taylor' },
      { option: 'tavik', label: 'Tavik' },
      { option: 'tbags-los-angeles', label: 'Tbags Los Angeles' },
      { option: 'temperley-london', label: 'Temperley London' },
      { option: 'the-bar', label: 'The Bar' },
      { option: 'the-basic-line', label: 'The basic line' },
      { option: 'the-frankie-shop', label: 'The Frankie Shop' },
      { option: 'the-kooples', label: 'The Kooples' },
      { option: 'the-line-by-k', label: 'The Line by K' },
      { option: 'the-north-face', label: 'The North Face' },
      { option: 'the-range', label: 'The Range' },
      { option: 'the-sei', label: 'The Sei' },
      { option: 'theory', label: 'Theory' },
      { option: 'thought-clothing', label: 'Thought Clothing' },
      { option: 'three-graces-london', label: 'Three Graces London' },
      { option: 'tiare-hawaii', label: 'Tiare Hawaii' },
      { option: 'tiranesh', label: 'Tiranesh' },
      { option: 'tlc-sport', label: 'TLC Sport' },
      { option: 'toccin', label: 'Toccin' },
      { option: 'toit-volant', label: 'Toit Volant' },
      { option: 'tom-ford', label: 'Tom Ford' },
      { option: 'tommy-hilfiger', label: 'Tommy Hilfiger' },
      { option: 'toms', label: 'Toms' },
      { option: 'topshop', label: 'Topshop' },
      { option: 'toribio', label: 'Toribio' },
      { option: 'tory-burch', label: 'Tory Burch' },
      { option: 'tove', label: 'TOVE' },
      { option: 'trista', label: 'Trista' },
      { option: 'tropicca', label: 'Tropicca' },
      { option: 'tularosa', label: 'Tularosa' },
      { option: 'twenty-montreal', label: 'TWENTY Montreal' },
      { option: 'ulla-johnson', label: 'Ulla Johnson' },
      { option: 'uma', label: 'Uma' },
      { option: 'under-armour', label: 'Under Armour' },
      { option: 'understated-leather', label: 'Understated Leather' },
      { option: 'uniqlo', label: 'Uniqlo' },
      { option: 'unttld', label: 'UNTTLD' },
      { option: 'urban-outfitters', label: 'Urban Outfitters' },
      { option: 'uro', label: 'URO' },
      { option: 'utzon', label: 'UTZON' },
      { option: 'utzon-cph', label: 'Utzon CPH' },
      { option: 'valentino', label: 'Valentino' },
      { option: 'valeria-anastasia', label: 'Valeria Anastasia' },
      { option: 'valeria-larr', label: 'Valeria Larr' },
      { option: 'vanessa-bruno', label: 'Vanessa Bruno' },
      { option: 'vanessa-mooney', label: 'VANESSA MOONEY' },
      { option: 'vans', label: 'Vans' },
      { option: 'varley', label: 'Varley' },
      { option: 'veja', label: 'Veja' },
      { option: 'venus-de-tierra', label: 'Venus de Tierra' },
      { option: 'verdi', label: 'Verdi' },
      { option: 'veronica-beard', label: 'Veronica Beard' },
      { option: 'versace', label: 'Versace' },
      { option: 'victoria-beckham', label: 'Victoria Beckham' },
      { option: 'vince', label: 'Vince' },
      { option: 'vincetta', label: 'Vincetta' },
      { option: 'vintage', label: 'Vintage' },
      { option: 'vita-kin', label: 'Vita Kin' },
      { option: 'vitamina-swim', label: 'Vitamina Swim' },
      { option: 'vivetta', label: 'Vivetta' },
      { option: 'vix-swimwear', label: 'Vix Swimwear' },
      { option: 'volcom', label: 'Volcom' },
      { option: 'von-dutch', label: 'Von Dutch' },
      { option: 'voz', label: 'VOZ' },
      { option: 'waimari', label: 'Waimari' },
      { option: 'wes-gordon', label: 'Wes Gordon' },
      { option: 'westward-leaning', label: 'Westward Leaning' },
      { option: 'weworewhat', label: 'WeWoreWhat' },
      { option: 'white-fox-boutique', label: 'White Fox Boutique' },
      { option: 'whitney-port-x-coze', label: 'Whitney Port x Coze' },
      { option: 'wildheart', label: 'Wildheart' },
      { option: 'with-j-an', label: 'With Jéan' },
      { option: 'wolford', label: 'Wolford' },
      { option: 'won-hundred', label: 'Won Hundred' },
      { option: 'wone', label: 'WONE' },
      { option: 'working-title', label: 'Working Title' },
      { option: 'wrangler', label: 'Wrangler' },
      { option: 'x-rena', label: 'Xírena' },
      { option: 'y-3', label: 'Y-3' },
      { option: 'yakampot', label: 'Yakampot' },
      { option: 'yeezy', label: 'Yeezy' },
      { option: 'yfb-clothing', label: 'YFB CLOTHING' },
      { option: 'yumi-kim', label: 'Yumi Kim' },
      { option: 'zadig-voltaire', label: 'Zadig & Voltaire' },
      { option: 'zara', label: 'Zara' },
      { option: 'zeynep-arcay', label: 'Zeynep Arcay' },
      { option: 'zhivago', label: 'Zhivago' },
      { option: 'zimmermann', label: 'Zimmermann' },
    ],
    saveConfig: {
      label: 'Marca',
      placeholderMessage: 'Selecciona una marca…',
      isRequired: true,
    },
    filterConfig: {
      indexForSearch: true,
      showFilter: true,
      filterType: 'SelectMultipleFilter',
      searchMode: 'has_any',
      label: 'Marca',
      group: 'primary',
    },
    showConfig: {
      label: 'Marca',
      isDisplay: true,
    },
  },
  // {
  //   "scope": "public",
  //   "label": "Gears",
  //   "key": "gears",
  //   "schemaType": "long",
  //   "numberConfig": {
  //     "minimum": 1,
  //     "maximum": 24
  //   },
  //   "filterConfig": {
  //     "indexForSearch": true,
  //     "group": "primary",
  //     "label": "Gears"
  //   }
  // }
  // {
  //   key: 'bikeType',
  //   scope: 'public',
  //   schemaType: 'enum',
  //   enumOptions: [
  //     { option: 'city-bikes', label: 'City bikes' },
  //     { option: 'electric-bikes', label: 'Electric bikes' },
  //     { option: 'mountain-bikes', label: 'Mountain bikes' },
  //     { option: 'childrens-bikes', label: "Children's bikes" },
  //   ],
  //   categoryConfig: {
  //     limitToCategoryIds: true,
  //     categoryIds: ['cats'],
  //   },
  //   filterConfig: {
  //     showFilter: true,
  //     filterType: 'SelectMultipleFilter', //'SelectSingleFilter',
  //     label: 'Bike type',
  //     group: 'primary',
  //   },
  //   showConfig: {
  //     label: 'Bike type',
  //     isDetail: true,
  //   },
  //   saveConfig: {
  //     label: 'Bike type',
  //     placeholderMessage: 'Select an option…',
  //     isRequired: true,
  //     requiredMessage: 'You need to select a bike type.',
  //   },
  // },
  // {
  //   key: 'tire',
  //   scope: 'public',
  //   schemaType: 'enum',
  //   enumOptions: [
  //     { option: '29', label: '29' },
  //     { option: '28', label: '28' },
  //     { option: '27', label: '27' },
  //     { option: '26', label: '26' },
  //     { option: '24', label: '24' },
  //     { option: '20', label: '20' },
  //     { option: '18', label: '18' },
  //   ],
  //   filterConfig: {
  //     showFilter: true,
  //     label: 'Tire size',
  //     group: 'secondary',
  //   },
  //   showConfig: {
  //     label: 'Tire size',
  //     isDetail: true,
  //   },
  //   saveConfig: {
  //     label: 'Tire size',
  //     placeholderMessage: 'Select an option…',
  //     isRequired: true,
  //     requiredMessage: 'You need to select a tire size.',
  //   },
  // },
  // {
  //   key: 'brand',
  //   scope: 'public',
  //   schemaType: 'enum',
  //   enumOptions: [
  //     { option: 'cube', label: 'Cube' },
  //     { option: 'diamant', label: 'Diamant' },
  //     { option: 'ghost', label: 'GHOST' },
  //     { option: 'giant', label: 'Giant' },
  //     { option: 'kalkhoff', label: 'Kalkhoff' },
  //     { option: 'kona', label: 'Kona' },
  //     { option: 'otler', label: 'Otler' },
  //     { option: 'vermont', label: 'Vermont' },
  //   ],
  //   filterConfig: {
  //     showFilter: true,
  //     label: 'Brand',
  //     group: 'secondary',
  //   },
  //   showConfig: {
  //     label: 'Brand',
  //     isDetail: true,
  //   },
  //   saveConfig: {
  //     label: 'Brand',
  //     placeholderMessage: 'Select an option…',
  //     isRequired: true,
  //     requiredMessage: 'You need to select a brand.',
  //   },
  // },
  // {
  //   key: 'accessories',
  //   scope: 'public',
  //   schemaType: 'multi-enum',
  //   enumOptions: [
  //     { option: 'bell', label: 'Bell' },
  //     { option: 'lights', label: 'Lights' },
  //     { option: 'lock', label: 'Lock' },
  //     { option: 'mudguard', label: 'Mudguard' },
  //   ],
  //   filterConfig: {
  //     showFilter: true,
  //     label: 'Accessories',
  //     searchMode: 'has_all',
  //     group: 'secondary',
  //   },
  //   showConfig: {
  //     label: 'Accessories',
  //   },
  //   saveConfig: {
  //     label: 'Accessories',
  //     placeholderMessage: 'Select an option…',
  //     isRequired: false,
  //   },
  // },
  // // An example of how to use transaction type specific custom fields and private data.
  // {
  //   key: 'note',
  //   scope: 'public',
  //   schemaType: 'text',
  //   listingTypeConfig: {
  //     limitToListingTypeIds: true,
  //     listingTypeIds: ['product-selling'],
  //   },
  //   showConfig: {
  //     label: 'Extra notes',
  //   },
  //   saveConfig: {
  //     label: 'Extra notes',
  //     placeholderMessage: 'Some public extra note about this bike...',
  //   },
  // },
  // {
  //   key: 'privatenote',
  //   scope: 'private',
  //   schemaType: 'text',
  //   listingTypeConfig: {
  //     limitToListingTypeIds: true,
  //     listingTypeIds: ['daily-booking'],
  //   },
  //   saveConfig: {
  //     label: 'Private notes',
  //     placeholderMessage: 'Some private note about this bike...',
  //   },
  // },
];

///////////////////////////////////////////////////////////////////////
// Configurations related to listing types and transaction processes //
///////////////////////////////////////////////////////////////////////

// A presets of supported listing configurations
//
// Note 1: The listingTypes come from listingTypes asset nowadays by default.
//         To use this built-in configuration, you need to change the overwrite from configHelper.js
//         (E.g. use mergeDefaultTypesAndFieldsForDebugging func)
// Note 2: transaction type is part of listing type. It defines what transaction process and units
//         are used when transaction is created against a specific listing.

/**
 * Configuration options for listing experience:
 * - listingType:         Unique string. This will be saved to listing's public data on
 *                        EditListingWizard.
 * - label                Label for the listing type. Used as microcopy for options to select
 *                        listing type in EditListingWizard.
 * - transactionType      Set of configurations how this listing type will behave when transaction is
 *                        created.
 *   - process              Transaction process.
 *                          The process must match one of the processes that this client app can handle
 *                          (check src/util/transactions/transaction.js) and the process must also exists in correct
 *                          marketplace environment.
 *   - alias                Valid alias for the aforementioned process. This will be saved to listing's
 *                          public data as transctionProcessAlias and transaction is initiated with this.
 *   - unitType             Unit type is mainly used as pricing unit. This will be saved to
 *                          transaction's protected data.
 *                          Recommendation: don't use same unit types in completely different processes
 *                          ('item' sold should not be priced the same as 'item' booked).
 * - stockType            This is relevant only to listings using default-purchase process.
 *                        If set to 'oneItem', stock management is not showed and the listing is
 *                        considered unique (stock = 1).
 *                        Possible values: 'oneItem', 'multipleItems', 'infiniteOneItem', and 'infiniteMultipleItems'.
 *                        Default: 'multipleItems'.
 * - availabilityType     This is relevant only to listings using default-booking process.
 *                        If set to 'oneSeat', seat management is not showed and the listing is
 *                        considered per person (seat = 1).
 *                        Possible values: 'oneSeat' and 'multipleSeats'.
 *                        Default: 'oneSeat'.
 * - priceVariations      This is relevant only to listings using default-booking process.
 *   - enabled:             If set to true, price variations are enabled.
 *                          Default: false.
 * - defaultListingFields These are tied to transaction processes. Different processes have different flags.
 *                        E.g. default-inquiry can toggle price and location to true/false value to indicate,
 *                        whether price (or location) tab should be shown. If defaultListingFields.price is not
 *                        explicitly set to _false_, price will be shown.
 *                        If the location or pickup is not used, listing won't be returned with location search.
 *                        Use keyword search as main search type if location is not enforced.
 *                        The payoutDetails flag allows provider to bypass setting of payout details.
 *                        Note: customers can't order listings, if provider has not set payout details! Monitor
 *                        providers who have not set payout details and contact them to ensure that they add the details.
 * - transactionFields    You can define an array of custom transaction fields for each listing type. Each transaction field
 *                        should have the following attributes:
 *                        - key (string)
 *                        - label (string)
 *                        - showTo (string, options: 'customer', 'provider'). Option 'provider' is only used for negotiation process.
 *                        - schemaType (string, options: 'enum', 'multi-enum', 'text', 'long', 'boolean', 'youtubeVideoUrl')
 *                        - saveConfig (object, optional,  { required: true })
 *                        - schema specific attributes:
 *                          - numberConfig (object, for schemaType: 'long'): { minimum: number, maximum: number }
 *                          - enumOptions (array, for schemaType: 'enum', 'multi-enum'): [{ label: string, option: string }]
 */

export const listingTypes = [
  // // Here are some examples of listingTypes
  // // TODO: SearchPage does not work well if both booking and product selling are used at the same time
  // {
  //   listingType: 'daily-booking',
  //   label: 'Daily booking',
  //   transactionType: {
  //     process: 'default-booking',
  //     alias: 'default-booking/release-1',
  //     unitType: 'day',
  //   },
  //   availabilityType: 'oneSeat',
  //   defaultListingFields: {
  //     location: true,
  //     payoutDetails: true,
  //   },
  //   transactionFields: [
  //     {
  //       showTo: 'customer',
  //       label: 'Extra requests for the hosts',
  //       key: 'requests',
  //       schemaType: 'text',
  //     },
  //     {
  //       showTo: 'customer',
  //       label: 'Are you traveling with minors?',
  //       key: 'minors',
  //       schemaType: 'boolean',
  //     },
  //     {
  //       showTo: 'customer',
  //       numberConfig: {
  //         minimum: 1,
  //         maximum: 10,
  //       },
  //       label: 'How many people are staying at the venue',
  //       key: 'peopleStaying',
  //       schemaType: 'long',
  //       saveConfig: {
  //         required: true,
  //       },
  //     },
  //     {
  //       showTo: 'customer',
  //       enumOptions: [
  //         {
  //           label: 'Morning cleanup (10am-12am)',
  //           option: 'morning',
  //         },
  //         {
  //           label: 'Afternoon cleanup (2pm-4pm)',
  //           option: 'afternoon',
  //         },
  //       ],
  //       label: 'Schedule preference',
  //       key: 'schedulePreference',
  //       schemaType: 'enum',
  //     },
  //     {
  //       showTo: 'customer',
  //       enumOptions: [
  //         {
  //           label: 'Vegetarian',
  //           option: 'vegetarian',
  //         },
  //         {
  //           label: 'Vegan',
  //           option: 'vegan',
  //         },
  //         {
  //           label: 'Gluten free',
  //           option: 'glutenFree',
  //         },
  //         {
  //           label: 'No caffeine',
  //           option: 'decaf',
  //         },
  //         {
  //           label: 'Nut free',
  //           option: 'nutFree',
  //         },
  //         {
  //           label: 'Dairy free',
  //           option: 'dairyFree',
  //         },
  //       ],
  //       label: 'Dietary preferences',
  //       key: 'dietaryPreferences',
  //       schemaType: 'multi-enum',
  //     },
  //   ],
  // },
  // {
  //   listingType: 'nightly-booking',
  //   label: 'Nightly booking',
  //   transactionType: {
  //     process: 'default-booking',
  //     alias: 'default-booking/release-1',
  //     unitType: 'night',
  //   },
  // },
  // {
  //   listingType: 'hourly-booking',
  //   label: 'Hourly booking',
  //   transactionType: {
  //     process: 'default-booking',
  //     alias: 'default-booking/release-1',
  //     unitType: 'hour',
  //   },
  // },
  // {
  //   listingType: 'product-selling',
  //   label: 'Sell bicycles',
  //   transactionType: {
  //     process: 'default-purchase',
  //     alias: 'default-purchase/release-1',
  //     unitType: 'item',
  //   },
  //   stockType: 'multipleItems',
  //   defaultListingFields: {
  //     shipping: true,
  //     pickup: true,
  //     payoutDetails: true,
  //   },
  // },
  // {
  //   listingType: 'inquiry',
  //   label: 'Inquiry',
  //   transactionType: {
  //     process: 'default-inquiry',
  //     alias: 'default-inquiry/release-1',
  //     unitType: 'inquiry',
  //   },
  //   defaultListingFields: {
  //     price: false,
  //     location: true,
  //   },
  // },
];

// SearchPage can enforce listing query to only those listings with valid listingType
// However, it only works if you have set 'enum' type search schema for the public data fields
//   - listingType
//
//  Similar setup could be expanded to 2 other extended data fields:
//   - transactionProcessAlias
//   - unitType
//
// Read More:
// https://www.sharetribe.com/docs/how-to/manage-search-schemas-with-flex-cli/#adding-listing-search-schemas
export const enforceValidListingType = false;

// AV: render the labeled-slot photo form (front/back/horizontal/details).
// Set to 'gallery' to use the upstream free-form FieldArray gallery.
export const photoMode = 'slots';
