const USER_TYPES = {
  BRAND: 'studio-brand',
  BUYER: 'buyer',
  SELLER: 'creative-seller',
};

const COMMUNITY_STATUS = {
  APPLIED: 'APPLIED',
  APPROVED: 'APPROVED',
  WAITLISTED: 'WAITLISTED',
};

const SELLER_STATUS = {
  APPLIED: 'APPLIED',
  APPROVED: 'APPROVED',
  WAITLISTED: 'WAITLISTED',
};

const BRAND_MEMBERSHIP_TYPES = {
  BASIC: 'BASIC',
  TALENT_SUITE: 'TALENT_SUITE',
};
const SELLER_MEMBERSHIP_TYPES = {
  BASIC: 'BASIC',
  CONNECT: 'CONNECT',
  PRO: 'PRO',
};

const LISTING_TYPES = {
  PRODUCT: 'product-listing',
  SERVICE: 'service-listing',
  PORTFOLIO: 'portfolio-showcase',
  PROFILE: 'profile-listing',
};

const USER_UPDATE_TYPE = {
  NO_CHANGES: 'NO_CHANGES',
  // Profile changes
  PROFILE_EMAIL: 'PROFILE_EMAIL',
  PROFILE_IDENTITY_PROVIDER: 'PROFILE_IDENTITY_PROVIDER',
  PROFILE_COMMUNITY_ID: 'PROFILE_COMMUNITY_ID',
  PROFILE_STUDIO_ID: 'PROFILE_STUDIO_ID',
  PROFILE_IS_BRAND_ADMIN: 'PROFILE_IS_BRAND_ADMIN',
  PROFILE_BRAND_STUDIO_ID: 'PROFILE_BRAND_STUDIO_ID',
  PROFILE_INIT_COMMUNITY_ID: 'PROFILE_INIT_COMMUNITY_ID',
  PROFILE_INIT_STUDIO_ID: 'PROFILE_INIT_STUDIO_ID',
  PROFILE_INIT_IS_BRAND_ADMIN: 'PROFILE_INIT_IS_BRAND_ADMIN',
  PROFILE_INIT_BRAND_STUDIO_ID: 'PROFILE_INIT_BRAND_STUDIO_ID',
  // User Type changes
  USER_TYPE_BRAND_TO_BUYER: 'USER_TYPE_BRAND_TO_BUYER',
  USER_TYPE_BRAND_TO_SELLER: 'USER_TYPE_BRAND_TO_SELLER',
  USER_TYPE_BUYER_TO_BRAND: 'USER_TYPE_BUYER_TO_BRAND',
  USER_TYPE_BUYER_TO_SELLER: 'USER_TYPE_BUYER_TO_SELLER',
  USER_TYPE_SELLER_TO_BRAND: 'USER_TYPE_SELLER_TO_BRAND',
  USER_TYPE_SELLER_TO_BUYER: 'USER_TYPE_SELLER_TO_BUYER',
  USER_TYPE_INVALID_CHANGE: 'USER_TYPE_INVALID_CHANGE',
  // Community Status changes
  COMMUNITY_STATUS_APPLIED_TO_APPROVED: 'COMMUNITY_STATUS_APPLIED_TO_APPROVED',
  COMMUNITY_STATUS_APPLIED_TO_WAITLISTED: 'COMMUNITY_STATUS_APPLIED_TO_WAITLISTED',
  COMMUNITY_STATUS_APPROVED_TO_APPLIED: 'COMMUNITY_STATUS_APPROVED_TO_APPLIED',
  COMMUNITY_STATUS_APPROVED_TO_WAITLISTED: 'COMMUNITY_STATUS_APPROVED_TO_WAITLISTED',
  COMMUNITY_STATUS_WAITLISTED_TO_APPLIED: 'COMMUNITY_STATUS_WAITLISTED_TO_APPLIED',
  COMMUNITY_STATUS_WAITLISTED_TO_APPROVED: 'COMMUNITY_STATUS_WAITLISTED_TO_APPROVED',
  COMMUNITY_STATUS_INIT_AS_APPLIED: 'COMMUNITY_STATUS_INIT_AS_APPLIED',
  COMMUNITY_STATUS_INIT_AS_APPROVED: 'COMMUNITY_STATUS_INIT_AS_APPROVED',
  COMMUNITY_STATUS_INIT_AS_WAITLISTED: 'COMMUNITY_STATUS_INIT_AS_WAITLISTED',
  COMMUNITY_STATUS_INVALID_CHANGE: 'COMMUNITY_STATUS_INVALID_CHANGE',
  // Seller Status changes
  SELLER_STATUS_APPLIED_TO_APPROVED: 'SELLER_STATUS_APPLIED_TO_APPROVED',
  SELLER_STATUS_APPLIED_TO_WAITLISTED: 'SELLER_STATUS_APPLIED_TO_WAITLISTED',
  SELLER_STATUS_APPROVED_TO_APPLIED: 'SELLER_STATUS_APPROVED_TO_APPLIED',
  SELLER_STATUS_APPROVED_TO_WAITLISTED: 'SELLER_STATUS_APPROVED_TO_WAITLISTED',
  SELLER_STATUS_WAITLISTED_TO_APPLIED: 'SELLER_STATUS_WAITLISTED_TO_APPLIED',
  SELLER_STATUS_WAITLISTED_TO_APPROVED: 'SELLER_STATUS_WAITLISTED_TO_APPROVED',
  SELLER_STATUS_INIT_AS_APPLIED: 'SELLER_STATUS_INIT_AS_APPLIED',
  SELLER_STATUS_INIT_AS_APPROVED: 'SELLER_STATUS_INIT_AS_APPROVED',
  SELLER_STATUS_INIT_AS_WAITLISTED: 'SELLER_STATUS_INIT_AS_WAITLISTED',
  SELLER_STATUS_INVALID_CHANGE: 'SELLER_STATUS_INVALID_CHANGE',
};

// Check for null or undefined
function isValidField(value) {
  return value != null;
}

module.exports = {
  USER_TYPES,
  COMMUNITY_STATUS,
  SELLER_STATUS,
  BRAND_MEMBERSHIP_TYPES,
  SELLER_MEMBERSHIP_TYPES,
  USER_UPDATE_TYPE,
  LISTING_TYPES,
  isValidField,
};
